\documentclass{article}
\input{load_bibliotecas}

\begin{document}
\SweaveOpts{concordance=TRUE}

\scriptsize

\newgeometry{left=1cm,right=1cm, top=2cm}

\renewcommand*{\arraystretch}{1.9}
 \scriptsize
 \color{myblack}
 \centering
 
<<echo=FALSE, results=tex>>=
dir_loa <- gsub("(.+LOA).*", "\\1", getwd())

ANO_DOC <- as.numeric(readLines(paste(dir_loa, "/utils/ano.txt", sep = ""), warn = F))

dir_data <- paste(dir_loa, "/volume5/data", sep = "")

# INICIO TABELA

consolidado <- read.table(paste(dir_data, "/consolidado.txt", sep = ""),
  header = T, sep = "\t",
  quote = NULL, dec = ",", stringsAsFactors = FALSE
)

cat("\\noindent\\begin{longtable}[c]{m{0.1cm}m{0.1cm}m{0.8cm}|m{8cm}|m{2cm}|m{2cm}|m{2cm}}\n")

titulo <- "\\multicolumn{7}{c}{\\cellcolor{gray!50} \\textcolor{myblack} {\\normalsize \\textbf{DEMONSTRATIVO CONSOLIDADO DA DESPESA}}}\\TBstrut  \\\\[2ex]\n"

subtitulo <- paste(
  "\\multicolumn{3}{l}{\\textbf{Exercício: \\textcolor{myblack}{", ANO_DOC,
  "}}} & \\multicolumn{3}{c}{RECURSOS DE TODAS AS FONTES}& \\multicolumn{1}{r}{R\\$1,00} \\\\\n"
)

subtitulo1 <- "\\multicolumn{7}{l}{ORÇAMENTO FISCAL} \\\\\n"

cabecalho <- paste(
  "\\multicolumn{3}{l|}{\\textbf{ CÓDIGO}} & \\multicolumn{1}{l|}{\\textbf{ESPECIFICAÇÃO}} & ",
  "\\valorHeader{\\centering \\textbf{RECURSOS DO TESOURO}} &",
  "\\valorHeader{\\centering \\textbf{RECURSOS DE OUTRAS FONTES}} & ",
  "\\multicolumn{1}{c}{\\textbf{TOTAL}}\\\\"
)

cat(titulo)
cat("\\specialrule{1.5pt}{2pt}{0pt}\n")
cat(subtitulo)
cat(subtitulo1)
cat("\\specialrule{1pt}{0pt}{0pt}\n")
cat(cabecalho)
cat("\\hline\n")
cat("\\endfirsthead\n")

cat(titulo)
cat("\\specialrule{1.5pt}{2pt}{0pt}\n")
cat(subtitulo)
cat(subtitulo1)
cat("\\specialrule{1pt}{0pt}{0pt}\n")
cat(cabecalho)
cat("\\hline\n")
cat("\\endhead\n")
cat("\\endfoot\n")

cat("\\hline\n")

cat("\\hline\\hline\n")
cat("\\endlastfoot\n")

for (i in 1:nrow(consolidado)) {
  if (consolidado$codigo_texto[i] != "Total" & i < nrow(consolidado)) {
    # Os condicionais a seguir tem como objetivo identar os codigos de despesa de acordo com os itens isolados e totais
    if (substr(as.character(consolidado$codigo_texto[i]), 3, 3) == "0" | substr(as.character(consolidado$codigo_texto[i]), 3, 3) == "9") {
      cat("\\multicolumn{3}{l|}{\\textbf{", as.character(consolidado$codigo_texto[i]),
        "}} & \\multicolumn{1}{L{8cm}|}{\\textit{", as.character(consolidado$especificacao[i]),
        "}} & \\multicolumn{1}{r|}{", as.character(consolidado$recurso_tesouro[i]),
        "} & \\multicolumn{1}{r|}{", as.character(consolidado$outras_fontes[i]),
        "} &  \\multicolumn{1}{r}{", as.character(consolidado$total[i]), "}\\\\\n",
        sep = ""
      )
    } else if (substr(as.character(consolidado$codigo_texto[i]), 5, 6) == "00") {
      cat("\\multicolumn{1}{l}{} & \\multicolumn{2}{l|}{\\textbf{", as.character(consolidado$codigo_texto[i]),
        "}} & \\multicolumn{1}{L{8cm}|}{\\textit{", as.character(consolidado$especificacao[i]),
        "}} & \\multicolumn{1}{r|}{", as.character(consolidado$recurso_tesouro[i]),
        "} & \\multicolumn{1}{r|}{", as.character(consolidado$outras_fontes[i]),
        "} &  \\multicolumn{1}{r}{", as.character(consolidado$total[i]), "}\\\\\n",
        sep = ""
      )
    } else {
      cat("\\multicolumn{1}{l}{} & \\multicolumn{1}{l}{} & \\multicolumn{1}{l|}{", as.character(consolidado$codigo_texto[i]),
        "} & \\multicolumn{1}{L{8cm}|}{\\textit{", as.character(consolidado$especificacao[i]),
        "}} & \\multicolumn{1}{r|}{", as.character(consolidado$recurso_tesouro[i]),
        "} & \\multicolumn{1}{r|}{", as.character(consolidado$outras_fontes[i]),
        "} &  \\multicolumn{1}{r}{", as.character(consolidado$total[i]), "}\\\\\n",
        sep = ""
      )
    }
  }
  if (toupper(consolidado$codigo_texto[i]) == "TOTAL" & i == nrow(consolidado)) {
    cat("\\hline\n\\multicolumn{4}{c|}{\\textbf{", toupper(as.character(consolidado$codigo_texto[i])),
      "}} & \\multicolumn{1}{r|}{", as.character(consolidado$recurso_tesouro[i]),
      "} & \\multicolumn{1}{r|}{", as.character(consolidado$outras_fontes[i]),
      "} &  \\multicolumn{1}{r}{", as.character(consolidado$total[i]), "}\n",
      sep = ""
    )
  }
}

cat("\\end{longtable}\n")

# FIM TABELA
@


 \end{document}
