[packages]

[packages.sisor]

path = "https://raw.githubusercontent.com/splor-mg/dados-ppo-2027/main/datapackage.json"
resources = [
  "base_categoria_pessoal",
  "base_detalhamento_obras",
  "base_orcam_despesa_item_fiscal",
  "base_orcam_receita_fiscal",
  "base_qdd_fiscal",
  "base_qdd_investimento",
  "base_repasse_recursos"
]

[packages.sigplan]

path = "https://raw.githubusercontent.com/splor-mg/dados-ppo-2027/main/datapackage.json"
resources = ["acoes_planejamento"]

[packages.apoio]

path = "https://raw.githubusercontent.com/splor-mg/dados-volumes-loa/df90c8ff5747a1964f8f1bc693b882c31b3dbf31/datapackage.yaml"

[packages.fonte_stn]

path = "https://raw.githubusercontent.com/splor-mg/matriz-fonte-stn-dadosmg/6b09828d6489eb0342188013b57219b9d9f236c9/datapackage.yaml"
resources = ["fonte_stn"]

[packages.qdd_fiscal_fonte_95]

path = "https://raw.githubusercontent.com/splor-mg/dados-qdd-fonte-95/9a55eecaa2c2f404a6bc5e63d865c0df00275a01/datapackage.json"
