\documentclass{article}
\input{load_bibliotecas}

\begin{document}
\SweaveOpts{concordance=TRUE}

\pagestyle{empty}
\newgeometry{bottom=1cm,top=1cm,left=1.5cm,right=1.5cm}


<<results=tex,echo=FALSE>>=
  
  dir_loa = gsub("(.+LOA).*", "\\1", getwd())
  dir_data = paste0(dir_loa, "/volume1/data")
  ANO_DOC = as.numeric(readLines(paste0(dir_loa, "/utils/ano.txt"), warn = F))
  source(paste0(dir_loa, "/utils/funcoes.R"), encoding = "UTF-8")

  # INICIO TABELA 

  banco = ler_banco_txt(paste0(dir_data, "/T12_DCGF_Demonstrativo_Evolucao_Despesa_Categoria_Economica.txt"))

  anos = sort(as.numeric(gsub("VL_DESP_(\\d{4})", "\\1", names(banco)[grepl("^VL.+", names(banco))])))

  cat("\\renewcommand*{\\arraystretch}{1.9}\n")
  cat("\\scriptsize\n")
  cat("\\color{myblack}\n")
  cat("\\centering\n")

  cat("\\noindent\\begin{longtable}[c]{",
      "m{4cm}|m{2cm}|m{1.5cm}|m{2cm}|m{1.5cm}|m{2cm}|m{1.5cm}}\n", sep="")

  titulo1= paste0("\\multicolumn{7}{c}{\\cellcolor{gray!50} \\textcolor{myblack} {\\small \\textbf{",
                  "DEMONSTRATIVO DA EVOLUÇÃO DA DESPESA POR CATEGORIA ECONÔMICA}}} \\\\\n")
 
  titulo2= paste0("\\multicolumn{7}{c}{\\cellcolor{gray!50} \\textcolor{myblack} {\\footnotesize \\textbf{",
                  "Período ", min(anos), "-", max(anos) ,"}}}  \\\\\n")
  
  
  titulo3= paste0("\\multicolumn{7}{c}{\\cellcolor{gray!50} \\textcolor{myblack} {\\small \\textbf{",
                  "(Art. 22, Inciso III da Lei 4.320/64)}}}  \\\\\n")
 
  subtitulo1 = paste0("\\multicolumn{2}{l}{\\textbf{ORÇAMENTO FISCAL}} & ",
                      "\\multicolumn{5}{r}{\\textbf{RECURSOS DE TODAS AS FONTES}} \\\\\n")
  subtitulo2 = paste("\\multicolumn{1}{l}{\\textbf{Exercício: \\textcolor{myblack}{ ",
                     ANO_DOC , "}}} & \\multicolumn{6}{r}{\\textbf{R\\$1,00}} \\\\\n")
 
  cat(titulo1)
  cat(titulo2)
  cat(titulo3)
  cat("\\specialrule{1.5pt}{0pt}{0pt}\n")
  cat(subtitulo1)
  cat(subtitulo2)
  cat("\\specialrule{1pt}{0pt}{0pt}\n")
 
  cabecalho1 = paste0("\\multicolumn{1}{L{4cm}|}{\\multirow{2}{*}{\\textbf{ESPECIFICAÇÃO}}} & ",
                      "\\multicolumn{2}{c|}{ \\textbf{", anos[1], "}} & ",
                      "\\multicolumn{2}{c|}{ \\textbf{", anos[2], "}} & ",
                      "\\multicolumn{2}{c}{ \\textbf{",  anos[3], "}} \\\\\n")

  cabecalho2 = paste0(" & \\multicolumn{1}{C{2.5cm}|}{ \\textbf{Despesa Realizada}} & ",
                      "\\multicolumn{1}{C{1.5cm}|}{ \\textbf{\\%}} & ",
                      "\\multicolumn{1}{C{2.5cm}|}{ \\textbf{Despesa Orçada}} & ",
                      "\\multicolumn{1}{C{1.5cm}|}{ \\textbf{\\%}} & ",
                      "\\multicolumn{1}{C{2.5cm}|}{ \\textbf{Despesa Estimada}} & ",
                      "\\multicolumn{1}{C{1.5cm}}{ \\textbf{\\%}} \\\\\n")
                      
  
  cat(cabecalho1)
  cat("\\cline{2-7}\n")
  cat(cabecalho2)
  cat("\\hline\n")
  

  for(i in 1:nrow(banco)){

    linha = as.vector(banco[i, ])

    if(grepl("^\\d{1}0.*", linha[["ordem"]])){

      if(linha[["ordem"]]==100) cat("\\hline\\hline\\hline\n")

      cat("\\multicolumn{1}{L{4cm}|}{ \\textbf{", linha[["espec"]],
          "}} & \\multicolumn{1}{R{2.5cm}|}{ \\textbf{", negativoContabil(linha[[paste0("VL_DESP_", anos[1])]]),
          "}} & \\multicolumn{1}{R{1.5cm}|}{ \\textbf{", linha[[paste0("perc_", anos[1])]],
          "\\%}} & \\multicolumn{1}{R{2.5cm}|}{ \\textbf{", negativoContabil(linha[[paste0("VL_DESP_", anos[2])]]),
          "}} & \\multicolumn{1}{R{1.5cm}|}{ \\textbf{", linha[[paste0("perc_", anos[2])]],
          "\\%}} & \\multicolumn{1}{R{2.5cm}|}{ \\textbf{", negativoContabil(linha[[paste0("VL_DESP_", anos[3])]]),
          "}} & \\multicolumn{1}{R{1.5cm}}{ \\textbf{",  linha[[paste0("perc_", anos[3])]], "\\%}} \\\\\n", sep="")
          

      } else{

        cat("\\multicolumn{1}{@{\\hspace{2em}}L{4cm}|}{", linha[["espec"]],
          "} & \\multicolumn{1}{R{2.5cm}|}{", negativoContabil(linha[[paste0("VL_DESP_", anos[1])]]),
          "} & \\multicolumn{1}{R{1.5cm}|}{", linha[[paste0("perc_", anos[1])]],
          "\\%} & \\multicolumn{1}{R{2.5cm}|}{", negativoContabil(linha[[paste0("VL_DESP_", anos[2])]]),
          "} & \\multicolumn{1}{R{1.5cm}|}{", linha[[paste0("perc_", anos[2])]],
          "\\%} & \\multicolumn{1}{R{2.5cm}|}{", negativoContabil(linha[[paste0("VL_DESP_", anos[3])]]),
          "} & \\multicolumn{1}{R{1.5cm}}{",  linha[[paste0("perc_", anos[3])]], "\\%} \\\\\n", sep="")
        
      }
  }
  
  cat("\\hline\\hline\\hline\n")
  
  cat("\\end{longtable}\n")

  # NOTAS DE RODAPÉ
  
  cat("\\raggedright\n")
  cat("\\fontsize{7pt}{10pt}\\selectfont {FONTE:", min(anos), "Armazém Siafi.} \\\\\n")
  
  cat("\\fontsize{7pt}{10pt}\\selectfont {", max(anos)-1, "e", max(anos), 
      "Armazém Sisor.} \\\\\n")
  
  cat("\\fontsize{7pt}{10pt}\\selectfont {ELABORAÇÃO: DCAF/SCPPO/SEPLAG}\\\\\n")
  
  cat("\\fontsize{7pt}{10pt}\\selectfont {NOTA: Com intuito de evitar a dupla",
      "contagem na elaboração desse relatório, foram desconsiderados os valores referentes às operações",
      "intra-orçamentárias.}\\\\\n")
  
  # FIM TABELA

@


\end{document}
