\documentclass{article}
\input{load_bibliotecas}

\begin{document}
\SweaveOpts{concordance=TRUE}

\pagestyle{empty}
\newgeometry{bottom=1cm,top=1cm,left=1.5cm,right=1.5cm}


<<results=tex,echo=FALSE>>=
  
  dir_loa = gsub("(.+LOA).*", "\\1", getwd())
  dir_data = paste0(dir_loa, "/volume1/data")
  ANO_DOC = as.numeric(readLines(paste0(dir_loa, "/utils/ano.txt"), warn = F))
  source(paste0(dir_loa, "/utils/funcoes.R"), encoding = "UTF-8")

  # INICIO TABELA 

  banco = ler_banco_txt(paste0(dir_data, "/T13_DCGF_Demonstrativo_Consolidado_Despesa.txt"))

  cat("\\renewcommand*{\\arraystretch}{1.9}\n")
  cat("\\scriptsize\n")
  cat("\\color{myblack}\n")
  cat("\\centering\n")

  cat("\\noindent\\begin{longtable}[c]{m{5cm}|m{4cm}|m{4cm}|m{4cm}}\n", sep="")

  titulo1= paste0("\\multicolumn{4}{c}{\\cellcolor{gray!50} \\textcolor{myblack} {\\small \\textbf{",
                  "DEMONSTRATIVO CONSOLIDADO DA DESPESA}}} \\\\\n")
 
  titulo2= paste0("\\multicolumn{4}{c}{\\cellcolor{gray!50} \\textcolor{myblack} {\\small \\textbf{",
                  base_legal("T13_DCGF_Demonstrativo_Consolidado_Despesa"),
                  "}}}  \\\\\n")
 
  subtitulo = paste("\\multicolumn{1}{l}{\\textbf{Exercício: \\textcolor{myblack}{ ",
                     ANO_DOC , "}}} & \\multicolumn{3}{r}{\\textbf{R\\$1,00}} \\\\\n")
 
  cabecalho = paste0("\\multicolumn{1}{L{5cm}|}{ \\textbf{ESPECIFICAÇÃO}} & ",
                     "\\multicolumn{1}{C{4cm}|}{ \\textbf{RECURSOS DO TESOURO}} & ",
                     "\\multicolumn{1}{C{4cm}|}{ \\textbf{RECURSOS DE OUTRAS FONTES}} & ",
                     "\\multicolumn{1}{C{4cm}}{ \\textbf{TOTAL}} \\\\\n")
  
  cat(titulo1)
  cat(titulo2)
  cat("\\specialrule{1.5pt}{0pt}{0pt}\n")
  cat(subtitulo)
  cat("\\specialrule{1pt}{0pt}{0pt}\n")
  cat(cabecalho)
  cat("\\hline\n")
  
  for(i in 1:nrow(banco)){

    linha = as.list(banco[i, ])

    if(grepl("^\\d{1}0.*", linha[["ordem"]])){

      if(linha[["ordem"]]==100) cat("\\hline\\hline\\hline\n")

      cat("\\multicolumn{1}{L{5cm}|}{ \\textbf{", linha[["espec"]],
          "}} & \\multicolumn{1}{R{4cm}|}{ \\textbf{", negativoContabil(linha[["tesouro"]]),
          "}} & \\multicolumn{1}{R{4cm}|}{ \\textbf{", negativoContabil(linha[["outras"]]),
          "}} & \\multicolumn{1}{R{4cm}}{ \\textbf{", negativoContabil(linha[["total"]]), "}} \\\\\n", sep="")
          

      } else{

        cat("\\multicolumn{1}{@{\\hspace{2em}}L{5cm}|}{", linha[["espec"]],
          "} & \\multicolumn{1}{R{4cm}|}{", negativoContabil(linha[["tesouro"]]),
          "} & \\multicolumn{1}{R{4cm}|}{", negativoContabil(linha[["outras"]]),
          "} & \\multicolumn{1}{R{4cm}}{", negativoContabil(linha[["total"]]), "} \\\\\n", sep="")
        
      }
  }
  
  cat("\\hline\\hline\\hline\n")
  
  cat("\\end{longtable}\n")

  # NOTAS DE RODAPÉ
  
  cat("\\raggedright\n")
  cat("\\fontsize{7pt}{10pt}\\selectfont {FONTE: Armazém Sisor.} \\\\\n")
  cat("\\fontsize{7pt}{10pt}\\selectfont {ELABORAÇÃO: DCAF/SCPPO/SEPLAG}\\\\\n")
  cat("\\fontsize{7pt}{10pt}\\selectfont {NOTA: Excepcionalmente, em 2023,",
      "foi destinado o valor de R\\$ 5.675.431,00 via emenda parlamentar (Indicador de Procedência - IPU 8) à Reserva de Contingência.",
      "Entretanto, apesar desse montante compor a referida reserva, optou-se em contabilizar o recurso no grupo de despesa “OUTRAS DESPESAS CORRENTES”, respeitando-se a classificação orçamentária e o objeto do gasto da emenda.}\\\\\n")
  
  # FIM TABELA

@


\end{document}
