\documentclass{article}

\input{load_bibliotecas}

\begin{document}
\SweaveOpts{concordance=TRUE}

\renewcommand*{\arraystretch}{1.9}
 \scriptsize
 \color{myblack}
 \centering
 
 \newgeometry{bottom=0cm,top=0cm,left=1.5cm,right=2cm}
%  \thispagestyle{lscape}
%  \pagestyle{lscape}
 
 \begin{landscape}
 
<<results=tex, echo=FALSE>>=

  dir_loa = gsub("(.+LOA).*", "\\1", getwd())
  dir_latex = paste0(dir_loa, "/volume1/Rnw")
  dir_codigosR = paste0(dir_latex, "/CodigosR")
  dir_utils = paste0(dir_loa, "/utils/")
  dir_data = paste0(dir_loa, "/volume1/data")
  dir_bancos = paste0(dir_loa, "/bancos")

  ANO_DOC = as.numeric(readLines(paste(dir_utils, "/ano.txt", sep=""), warn = F))
  
  source(paste0(dir_utils, "funcoes.R"), encoding = "UTF-8")
  
  
  # INICIO TABELA
  
  arquivo = "/T14_DEMONSTRATIVO_DESPESA_FUNCAO_SUBFUNCAO_PROGRAMA_CONFORME_VINCULO_COM_RECURSOS.txt"
  
  suppressMessages(suppressWarnings(library(readr)))
  
  banco = read_delim(
    file = paste0(dir_data, arquivo),
    delim = '\t', 
    na = '',
    col_types = cols(.default = col_character())
    )

  banco = as.data.table(banco)

  cat("\\footnotesize\n")
  #cat("\\renewcommand*{\\arraystretch}{1.5}\n")

  cat("\\noindent\\begin{longtable}[c]{m{3pt}m{3pt}m{3pt}|m{8cm}|m{2.5cm}|m{3cm}|m{3cm}|m{3cm}}\n")


  titulo1 = paste0("\\multicolumn{8}{c}{\\cellcolor{gray!50} \\textcolor{myblack} {\\footnotesize ",
                   "\\textbf{DEMONSTRATIVO DA DESPESA POR FUNÇÃO, SUBFUNÇÃO E PROGRAMA CONFORME O VÍNCULO ",
                   "COM OS RECURSOS}}}\\TBstrut  \\\\[2ex]\n")

  titulo2 = paste0("\\multicolumn{8}{c}{\\cellcolor{gray!50} { \\textcolor{myblack}{ \\textbf{",
                   base_legal("T14_DEMONSTRATIVO_DESPESA_FUNCAO_SUBFUNCAO_PROGRAMA_CONFORME_VINCULO_COM_RECURSOS"),
                   "}}}}\\\\\n")

  subtitulo = paste0("\\multicolumn{7}{l}{\\scriptsize \\textbf{Exercício: \\textcolor{myblack}{", ANO_DOC ,
                    "}}} & \\multicolumn{1}{r}{\\scriptsize R\\$1,00} \\\\\n")


  cabecalho1 = paste("\\multicolumn{3}{c|}{\\textbf{CÓDIGO}} & ",
                     "\\multicolumn{1}{C{8cm}|}{\\multirow{2}{*}{\\textbf{ESPECIFICAÇÃO}}} & ",
                     "\\multicolumn{3}{|c|}{\\textbf{VALOR}} & ",
                     "\\multicolumn{1}{C{3cm}}{\\multirow{2}{*}{\\textbf{TOTAL}}} \\\\\n")

  cabecalho2 = paste("\\multicolumn{1}{c}{\\fonteSeis{FUN}} & \\multicolumn{1}{c}{\\fonteSeis{SUBF}} & ",
                     "\\multicolumn{1}{c|}{\\fonteSeis{PROG}} & & ",
                     "\\multicolumn{1}{|C{2.5cm}|}{ \\textbf{REC. ORDINÁRIOS}} & ",
                     "\\multicolumn{1}{C{3cm}|}{ \\textbf{REC. VINCULADOS}} & ",
                     "\\multicolumn{1}{C{3cm}|}{ \\textbf{REC. DIR. ARRECADADOS}} &  \\\\\n")

  cat(titulo1)
  cat(titulo2)
  cat("\\specialrule{1.5pt}{2pt}{0pt}\n")
  cat(subtitulo)
  cat("\\specialrule{1pt}{0pt}{0pt}\n")
 
  cat(cabecalho1)
  cat("\\cline{5-7}\n")
  cat(cabecalho2)
 
  cat("\\hline\n")
  cat("\\endfirsthead\n")
 
  cat(titulo1)
  cat(titulo2)
  cat("\\specialrule{1.5pt}{2pt}{0pt}\n")
  cat(subtitulo)
  cat("\\specialrule{1pt}{0pt}{0pt}\n")
 
  cat(cabecalho1)
  cat("\\cline{5-7}\n")
  cat(cabecalho2)
 
  cat("\\hline\n")
  cat("\\endhead\n")
  cat("\\endfoot\n")
  cat("\\hline\n")

  cat("\\hline\\hline\n")
  cat("\\endlastfoot\n")
 
    for(i in 1:nrow(banco)){
    
      if(toupper(banco[i, especificacao])=="TOTAL"){
      
        cat("\\hline \\hline\n")
        
        cat("\\multicolumn{4}{l|}{ \\textbf{", toupper(banco[i, especificacao]),
            "}} & \\multicolumn{1}{r|}{ \\textbf{", formatarNum(TratamentoNA(banco[i, ordinarios])), 
            "}} & \\multicolumn{1}{r|}{ \\textbf{", formatarNum(TratamentoNA(banco[i, vinculados])), 
            "}} & \\multicolumn{1}{r|}{ \\textbf{", formatarNum(TratamentoNA(banco[i, arrecadados])), 
            "}} & \\multicolumn{1}{r}{ \\textbf{", formatarNum(TratamentoNA(banco[i, total])), 
            "}} \\\\\n")
      
      } else{

          cat("\\multicolumn{1}{l}{ ", formatC(TratamentoNA(banco[i, funcao]), width = 2, flag = "0"),  
              "} & \\multicolumn{1}{l}{", formatC(TratamentoNA(banco[i, subfuncao]), width = 3, flag = "0"), 
              "} & \\multicolumn{1}{c|}{", formatC(TratamentoNA(banco[i, programa]), width = 3, flag = "0"),
              "} & \\multicolumn{1}{@{\\hspace{0.5em}}L{8cm}|}{", toupper(banco[i, especificacao]), 
              "} & \\multicolumn{1}{r|}{", formatarNum(TratamentoNA(banco[i, ordinarios])), 
              "} & \\multicolumn{1}{r|}{", formatarNum(TratamentoNA(banco[i, vinculados])), 
              "} & \\multicolumn{1}{r|}{", formatarNum(TratamentoNA(banco[i, arrecadados])), 
              "} & \\multicolumn{1}{r}{",  formatarNum(TratamentoNA(banco[i, total])), 
              "} \\\\\n", sep=" ")
      }
    }

 cat("\\end{longtable}\n")
 
# FIM TABELA


@

\end{landscape}
 
\end{document}
