\documentclass{article}
\input{load_bibliotecas}

\begin{document}
\SweaveOpts{concordance=TRUE}

\pagestyle{empty}
\newgeometry{bottom=1.5cm,top=1.5cm,left=1.5cm,right=1.5cm}


<<results=tex,echo=FALSE>>=
  
  dir_loa = gsub("(.+LOA).*", "\\1", getwd())
  dir_data = paste0(dir_loa, "/volume1/data")
  ANO_DOC = as.numeric(readLines(paste0(dir_loa, "/utils/ano.txt"), warn = F))
  source(paste0(dir_loa, "/utils/funcoes.R"), encoding = "UTF-8")

  # INICIO TABELA 

  banco = ler_banco_txt(paste0(dir_data, "/T19_DCGF_Demonstrativo_Aplicacao_Recursos_Amparo_Fomento_Pesquisa.txt"))

  cat("\\renewcommand*{\\arraystretch}{1.8}\n")
  cat("\\footnotesize\n")
  cat("\\color{myblack}\n")
  cat("\\centering\n")

  cat("\\noindent\\begin{longtable}[c]{m{2cm}|m{12cm}|m{3cm}}\n", sep="")

  titulo1= paste0("\\multicolumn{3}{c}{\\cellcolor{gray!50} \\textcolor{myblack} {\\footnotesize ",
                  "\\textbf{DEMONSTRATIVO DA APLICAÇÃO DE RECURSOS NO AMPARO E FOMENTO À PESQUISA}}} \\\\\n")
  
  titulo2= paste0("\\multicolumn{3}{c}{\\cellcolor{gray!50} \\textcolor{myblack} {\\footnotesize ",
                  "\\textbf{",
                  base_legal("T19_DCGF_Demonstrativo_Aplicacao_Recursos_Amparo_Fomento_Pesquisa"),
                  "}}} \\\\\n")
 
  subtitulo1 = paste0("\\multicolumn{3}{l}{\\textbf{ORÇAMENTO FISCAL}} \\\\\n")
                      
  
  subtitulo2 = paste("\\multicolumn{1}{l}{\\textbf{Exercício: \\textcolor{myblack}{ ",
                     ANO_DOC , "}}} & \\multicolumn{2}{r}{\\textbf{R\\$1,00}} \\\\\n")
 
  cabecalho = paste0("\\multicolumn{1}{L{2cm}|}{\\textbf{CÓDIGO}} & ",
                     "\\multicolumn{1}{C{12cm}|}{ \\textbf{ESPECIFICAÇÃO}} & ",
                     "\\multicolumn{1}{C{3cm}}{ \\textbf{VALOR}} \\\\\n")
                     
  cat(titulo1)
  cat(titulo2)
  cat("\\specialrule{1.5pt}{2pt}{0pt}\n")
  cat(subtitulo1)
  cat(subtitulo2)
  cat("\\specialrule{1pt}{0pt}{0pt}\n")
  cat(cabecalho)
  cat("\\hline\n")
  cat("\\endfirsthead\n")
 
  cat(titulo1)
  cat(titulo2)
  cat("\\specialrule{1.5pt}{2pt}{0pt}\n")
  cat(subtitulo1)
  cat(subtitulo2)
  cat("\\specialrule{1pt}{0pt}{0pt}\n")
  cat(cabecalho)
  cat("\\hline\n")
  cat("\\endhead\n")
  cat("\\endfoot\n")
  
  cat("\\hline\\hline\n")
  cat("\\endlastfoot\n")

  for(i in 1:nrow(banco)){

    linha = as.list(banco[i, ])

    if(linha[["cod"]] %in% as.character(1:5)){
      
      if(linha[["cod"]] %in% as.character(3:5)) cat("\\hline\n")

      cat("\\multicolumn{1}{C{2cm}|}{ \\textbf{ ",
          "}} & \\multicolumn{1}{L{12cm}|}{ \\textbf{", linha[["espec"]],
          "}} & \\multicolumn{1}{R{3cm}}{ \\textbf{", linha[["valor"]], "}}\\TBstrut \\\\ [3ex] \n", sep="")

      } else{

        cat("\\multicolumn{1}{C{2cm}|}{", linha[["cod"]],
          "} & \\multicolumn{1}{@{\\hspace{2em}}L{12cm}|}{", linha[["espec"]],
          "} & \\multicolumn{1}{R{3cm}}{", linha[["valor"]], "} \\\\\n", sep="")

      }
  }
  
  cat("\\hline\\hline\n")
  cat("\\end{longtable}\n")

  # NOTAS DE RODAPÉ
  
  cat("\\raggedright\n")
  cat("\\fontsize{7pt}{10pt}\\selectfont {FONTE: Armazém Sisor.} \\\\\n")
  cat("\\fontsize{7pt}{10pt}\\selectfont {ELABORAÇÃO: DCAF/SCPPO/SEPLAG}\\\\\n")
  

  # FIM TABELA

@

\end{document}
