\documentclass{article}
\input{load_bibliotecas}

\begin{document}
\SweaveOpts{concordance=TRUE}

\pagestyle{empty}
\newgeometry{bottom=1.5cm,top=1.5cm,left=1.5cm,right=1.5cm}


<<results=tex,echo=FALSE>>=
  
  dir_loa = gsub("(.+LOA).*", "\\1", getwd())
  dir_data = paste0(dir_loa, "/volume1/data")
  ANO_DOC = as.numeric(readLines(paste0(dir_loa, "/utils/ano.txt"), warn = F))
  source(paste0(dir_loa, "/utils/funcoes.R"), encoding = "UTF-8")

  # INICIO TABELA 

  banco = ler_banco_txt(paste0(dir_data, "/T20A_DCGF_Demonstrativo_Partic_Percentual_Pessoal_RCL_LRF.txt"))

  cat("\\renewcommand*{\\arraystretch}{1.8}\n")
  cat("\\footnotesize\n")
  cat("\\color{myblack}\n")
  cat("\\centering\n")

  cat("\\noindent\\begin{longtable}[c]{m{12cm}m{2cm}|m{3cm}}\n", sep="")

  titulo1= paste0("\\multicolumn{3}{c}{\\cellcolor{gray!50} \\textcolor{myblack} {\\footnotesize ",
                  "\\textbf{DEMONSTRATIVO DA PARTICIPAÇÃO PERCENTUAL DE PESSOAL NA RECEITA CORRENTE LÍQUIDA}}} \\\\\n")
  
  titulo2= paste0("\\multicolumn{3}{c}{\\cellcolor{gray!50} \\textcolor{myblack} {\\footnotesize ",
                  "\\textbf{(Art. 19 da Lei Complementar 101/2000 - LRF e Art. 7\\degree, ",
                  "Inciso VIII da Lei 24.218/2022 - LDO)}}}  \\\\\n")
 
  subtitulo1 = paste0("\\multicolumn{3}{l}{\\textbf{ORÇAMENTO FISCAL}} \\\\\n")
  
  subtitulo2 = paste("\\multicolumn{1}{l}{\\textbf{Exercício: \\textcolor{myblack}{ ",
                     ANO_DOC , "}}} & \\multicolumn{2}{r}{\\textbf{R\\$1,00}} \\\\\n")
 
  cabecalho = paste0("\\multicolumn{2}{c|}{ \\textbf{ESPECIFICAÇÃO}} & ",
                     "\\multicolumn{1}{C{3cm}}{ \\textbf{VALOR}} \\\\\n")
                     
  cat(titulo1)
  cat(titulo2)
  cat("\\specialrule{1.5pt}{2pt}{0pt}\n")
  cat(subtitulo1)
  cat(subtitulo2)
  cat("\\specialrule{1pt}{0pt}{0pt}\n")
  cat(cabecalho)
  cat("\\hline\n")
  cat("\\endfirsthead\n")
 
  cat(titulo1)
  cat(titulo2)
  cat("\\specialrule{1.5pt}{2pt}{0pt}\n")
  cat(subtitulo1)
  cat(subtitulo2)
  cat("\\specialrule{1pt}{0pt}{0pt}\n")
  cat(cabecalho)
  cat("\\hline\n")
  cat("\\endhead\n")
  cat("\\endfoot\n")
  
  cat("\\hline\\hline\n")
  cat("\\endlastfoot\n")

  for(i in 1:nrow(banco)){

    linha = as.list(banco[i, ])
  
  # Insere uma linha acima das linhas que iniciam com "Poder" e "TOTAL PESSOAL DO ESTADO"
    
  if(linha[["cod"]] %in% seq(3,11, 2)) cat(" & \\multicolumn{1}{r|}{} & \\multicolumn{1}{r}{} \\\\[-2ex]\n")

    if(linha[["cod"]] %in% c(1,2,12,13)){
      
      hspace_espec = ""
      colocarNegrito = 1
      
      if(linha[["cod"]] %in% 12:13){ 
        hspace_espec = "@{\\hspace{2em}}"
        colocarNegrito = 0
        }

      cat("\\multicolumn{1}{", hspace_espec, "L{12cm}}{ \\textbf{", linha[["espec"]],
          "}} & \\multicolumn{1}{C{2cm}|}{ \\textbf{", ifelse(linha[["perc"]]!="", paste0(linha[["perc"]], "\\%"), ""),
          "}} & \\multicolumn{1}{R{3cm}}{", aplicaNegrito(linha[["valor"]], colocarNegrito) , "} \\\\\n", sep="")
      
      if(linha[["cod"]]==1) cat("\\hline\n")

      } else{

        cat("\\multicolumn{1}{L{12cm}}{", linha[["espec"]],
            "} & \\multicolumn{1}{C{2cm}|}{ \\textbf{", ifelse(linha[["perc"]]!="", paste0(linha[["perc"]], "\\%"), ""),
            "}} & \\multicolumn{1}{R{3cm}}{", linha[["valor"]], "} \\\\\n", sep="")

      }
  }
  
  cat("\\hline\\hline\n")
  cat("\\end{longtable}\n")

  # NOTAS DE RODAPÉ
  
  cat("\\raggedright\n")
  cat("\\fontsize{7pt}{10pt}\\selectfont {FONTE: Armazém Sisor.} \\\\\n")
  cat("\\vskip 0.2cm\n")
  cat("\\fontsize{7pt}{10pt}\\selectfont {ELABORAÇÃO: DCAF/SCPPO/SEPLAG}\\\\\n")
  cat("\\vskip 0.2cm\n")
  cat("\\fontsize{7pt}{10pt}\\selectfont {Nota: Conforme disposto na Instrução Normativa n\\degree 01/2018, o",
      "Estado de Minas Gerais deixou de publicar o Demonstrativo da Participação Percentual de Pessoal na",
      "Receita Corrente Líquida disciplinado pela Instrução n\\degree 5/2001 – TCEMG.}\\\\\n")
  
  # FIM TABELA

@

\end{document}
