\documentclass{article}
\input{load_bibliotecas}

\begin{document}
\SweaveOpts{concordance=TRUE}

\pagestyle{empty}
\newgeometry{bottom=1.2cm,top=1.2cm,left=1.5cm,right=1.5cm}


<<results=tex,echo=FALSE>>=
  
  dir_loa = gsub("(.+LOA).*", "\\1", getwd())
  dir_data = paste0(dir_loa, "/volume1/data")
  ANO_DOC = as.numeric(readLines(paste0(dir_loa, "/utils/ano.txt"), warn = F))
  source(paste0(dir_loa, "/utils/funcoes.R"), encoding = "UTF-8")

  # INICIO TABELA 

  banco = ler_banco_txt(paste0(dir_data, "/T27_DCGF_Demonst_Despesas_UGEPREVI.txt"))

  cat("\\renewcommand*{\\arraystretch}{1.6}\n")
  cat("\\scriptsize\n")
  cat("\\color{myblack}\n")
  cat("\\centering\n")

  cat("\\noindent\\begin{longtable}[c]{m{13cm}|m{3cm}}\n", sep="")

  titulo1= paste0("\\multicolumn{2}{c}{\\cellcolor{gray!50} \\textcolor{myblack} {\\footnotesize ",
                  "\\textbf{DEMONSTRATIVO DA UNIDADE DE GESTÃO PREVIDENCIÁRIA INTEGRADA - UGEPREVI}}} \\\\\n")
  
  titulo2= paste("\\multicolumn{2}{C{18cm}}{\\cellcolor{gray!50} \\textcolor{myblack} {\\footnotesize",
                 "\\textbf{(Art. 7\\degree, Inciso X da Lei 24.218/2022 - LDO)}}}  \\\\\n")
 
  subtitulo1 = paste("\\multicolumn{1}{l}{\\textbf{Exercício: \\textcolor{myblack}{ ",
                     ANO_DOC , "}}} & \\multicolumn{1}{r}{\\textbf{R\\$1,00}} \\\\\n")
 
  cabecalho = paste0("\\multicolumn{1}{C{13cm}}{\\textbf{UNIDADE ORÇAMENTÁRIA / AÇÃO}} & ",
                     "\\multicolumn{1}{C{3cm}}{ \\textbf{VALOR ORÇADO}} \\\\\n")
  
  cat(titulo1)
  cat(titulo2)
  cat("\\specialrule{1.5pt}{2pt}{0pt}\n")
  cat(subtitulo1)
  cat("\\specialrule{1pt}{0pt}{0pt}\n")
  cat(cabecalho)
  cat("\\hline\\hline\n")
  cat("\\endfirsthead\n")
  
  cat(titulo1)
  cat(titulo2)
  cat("\\specialrule{1.5pt}{2pt}{0pt}\n")
  cat(subtitulo1)
  cat("\\specialrule{1pt}{0pt}{0pt}\n")
  cat(cabecalho)
  cat("\\hline\\hline\n")
  cat("\\endhead\n")
  cat("\\endfoot\n")
  
  cat("\\hline\\hline\n")
  cat("\\endlastfoot\n")
  
  for(i in 1:nrow(banco)){

    linha = as.list(banco[i, ])

    if(linha[["tipo"]]=="Poder"){
      
      cat("\\hline\n")
      cat("\\multicolumn{2}{c}{ \\textbf{ \\footnotesize{", linha[["espec"]], "}}} \\\\\n", sep="")

     } else if(linha[["tipo"]] %in% c("", "UO", "Subtotal")){

        if(linha[["tipo"]]=="") cat("\\hline\n")

        cat("\\multicolumn{1}{L{13cm}}{ \\textbf{", linha[["espec"]],
          "}} & \\multicolumn{1}{R{3cm}}{ \\textbf{", linha[["valor"]], "}} \\\\\n", sep="")

         } else{

        cat("\\multicolumn{1}{@{\\hspace{6em}}L{13cm}}{", linha[["espec"]],
          "} & \\multicolumn{1}{R{3cm}}{", linha[["valor"]], "} \\\\\n", sep="")
      }
   }
  
  cat("\\hline\\hline\n")
  cat("\\end{longtable}\n")

  # NOTAS DE RODAPÉ
  
  cat("\\vspace{-0.4cm} \\raggedright\n")
  cat("\\fontsize{7pt}{10pt}\\selectfont {FONTE: Armazém Sisor.} \\\\\n")
  cat("\\fontsize{7pt}{10pt}\\selectfont {ELABORAÇÃO: DCAF/SCPPO/SEPLAG}\\\\\n")
  
  # FIM TABELA

@

\end{document}
