\documentclass{article}
\input{load_bibliotecas}

\begin{document}
\SweaveOpts{concordance=TRUE}

\pagestyle{empty}
\newgeometry{bottom=1.5cm,top=1cm,left=1.5cm,right=1.5cm}


<<results=tex,echo=FALSE>>=
  options(scipen = 999)
  dir_loa = gsub("(.+LOA).*", "\\1", getwd())
  dir_data = paste0(dir_loa, "/volume1/data")
  ANO_DOC = as.numeric(readLines(paste0(dir_loa, "/utils/ano.txt"), warn = F))
  source(paste0(dir_loa, "/utils/funcoes.R"), encoding = "UTF-8")

  # INICIO TABELA 

  banco = ler_banco_txt(paste0(dir_data, "/T28_DCGF_PT1_Receita_prevista_e_realizada.txt"))

  titulo_demonstrativo = "DEMONSTRATIVO DOS PROGRAMAS FINANCIADOS COM RECURSOS PROVENIENTES DA UNIÃO"
  titulo2_demons = "(Art. 7\\degree, Inciso XX da Lei 24.218/2022 - LDO)"
  
  cat("\\renewcommand*{\\arraystretch}{1.8}\n")
  cat("\\scriptsize\n")
  cat("\\color{myblack}\n")
  cat("\\centering\n")

  # ====================================================================================================
  # 1. Receita prevista e realizada no exercício passado
  
  cat("\\noindent\\begin{longtable}[c]{m{2cm}|m{11cm}|m{2cm}m{2cm}}\n", sep="")

  titulo1= paste0("\\multicolumn{4}{c}{\\cellcolor{gray!50} \\textcolor{myblack} {\\footnotesize ",
                  "\\textbf{", titulo_demonstrativo,"}}} \\\\\n")
  
  titulo2= paste0("\\multicolumn{4}{c}{\\cellcolor{gray!50} \\textcolor{myblack} {\\footnotesize ",
                  "\\textbf{", titulo2_demons,"}}}  \\\\\n")
 
  subtitulo = paste0("\\multicolumn{4}{c}{\\textbf{Receita prevista e realizada no exercício de ", 
                      banco[1, ANO], "}} \\\\\n")
  
  
  cabecalho = paste0("\\multicolumn{2}{c|}{\\textbf{Classificação da Receita}} & ",
                     "\\multicolumn{1}{C{2cm}|}{ \\textbf{Valor Previsto Inicial}} & ",
                     "\\multicolumn{1}{C{2cm}}{ \\textbf{Valor Efetivado Ajustado}} \\\\\n")
                     
  cat(titulo1);  cat(titulo2)
  cat("\\specialrule{1.5pt}{2pt}{0pt}\n")
  cat(subtitulo)
  cat("\\specialrule{1pt}{0pt}{0pt}\n")
  cat(cabecalho)
  cat("\\hline\n")
  cat("\\endfirsthead\n")
 
  cat(titulo1);  cat(titulo2)
  cat("\\specialrule{1.5pt}{2pt}{0pt}\n")
  cat(subtitulo)
  cat("\\specialrule{1pt}{0pt}{0pt}\n")
  cat(cabecalho)
  cat("\\hline\n")
  cat("\\endhead\n")
  cat("\\endfoot\n")
  
  cat("\\hline\\hline\n")
  cat("\\endlastfoot\n")

  for(i in 1:nrow(banco)){

    linha = as.list(banco[i, ])

    if(linha[["RECEITA_DESC"]]=="TOTAL"){
      
      cat("\\hline\n")

      cat("\\multicolumn{2}{c|}{ \\textbf{", linha[["RECEITA_DESC"]],
          "}} & \\multicolumn{1}{R{2cm}|}{ \\textbf{", linha[["previsto"]],
          "}} & \\multicolumn{1}{R{2cm}}{ \\textbf{", linha[["efet_ajust"]], "}} \\\\\n", sep="")

      } else{

        cat("\\multicolumn{1}{C{2cm}|}{", formatReceita_COD(linha[["RECEITA_COD"]]),
            "} & \\multicolumn{1}{L{11cm}|}{", linha[["RECEITA_DESC"]],
            "} & \\multicolumn{1}{R{2cm}|}{", linha[["previsto"]],
            "} & \\multicolumn{1}{R{2cm}}{", linha[["efet_ajust"]], "} \\\\\n", sep="")

      }
  }
  
  cat("\\hline\\hline\n")
  cat("\\end{longtable}\n")

  # NOTAS DE RODAPÉ
  
  cat("\\raggedright\n")
  cat("\\fontsize{7pt}{10pt}\\selectfont {FONTE: Armazém Sisor.} \\\\\n")
  cat("\\fontsize{7pt}{10pt}\\selectfont {ELABORAÇÃO: DCAF/SCPPO/SEPLAG}\\\\\n")
  cat("\\fontsize{7pt}{10pt}\\selectfont {Nota: Foi considerado o valor da receita efetivada até o mês de ", 
      banco[1, paste(MES, ANO, sep="/")],"}\\\\\n", sep="")
  cat("\\fontsize{7pt}{10pt}\\selectfont {Na elaboração desse relatório foram consideradas as fontes de recurso ", 
      banco[1, FONTE_EXEC], ".}\\\\\n", sep="")
  
  # FIM TABELA

@


\end{document}
