\documentclass{article}
\input{load_bibliotecas}

\begin{document}
\SweaveOpts{concordance=TRUE}

\pagestyle{empty}
\newgeometry{bottom=1.5cm,top=1.5cm,left=1.5cm,right=1.5cm}


<<results=tex,echo=FALSE>>=
  options(scipen = 999)
  dir_loa = gsub("(.+LOA).*", "\\1", getwd())
  dir_data = paste0(dir_loa, "/volume1/data")
  ANO_DOC = as.numeric(readLines(paste0(dir_loa, "/utils/ano.txt"), warn = F))
  source(paste0(dir_loa, "/utils/funcoes.R"), encoding = "UTF-8")

  # INICIO TABELA 
  banco = as.data.table(readr::read_delim(
    file = paste0(dir_data, "/T28_DCGF_PT4_Despesa_prevista_LOA.txt"),
    delim = '\t', 
    locale = readr::locale(decimal_mark = ',', encoding = 'Latin1', grouping_mark = '.'),
    col_types = readr::cols(.default = 'c')
  ))
    
  #banco = ler_banco_txt()

  titulo_demonstrativo = "DEMONSTRATIVO DOS PROGRAMAS FINANCIADOS COM RECURSOS PROVENIENTES DA UNIÂO"
  titulo2_demons = "(Art. 7\\degree, Inciso XX da Lei 24.218/2022 - LDO)"
  
  cat("\\renewcommand*{\\arraystretch}{1.8}\n")
  cat("\\scriptsize\n")
  cat("\\color{myblack}\n")
  cat("\\centering\n")

  # ====================================================================================================
  # 1. Receita prevista e realizada no exercício passado
  
  cat("\\noindent\\begin{longtable}[c]{m{1cm}|m{1.5cm}|m{1cm}m{10cm}|m{2cm}}\n", sep="")

  titulo1= paste0("\\multicolumn{5}{c}{\\cellcolor{gray!50} \\textcolor{myblack} {\\footnotesize ",
                  "\\textbf{", titulo_demonstrativo,"}}} \\\\\n")
  
  titulo2= paste0("\\multicolumn{5}{c}{\\cellcolor{gray!50} \\textcolor{myblack} {\\footnotesize ",
                  "\\textbf{", titulo2_demons,"}}}  \\\\\n")
 
  subtitulo = paste0("\\multicolumn{5}{c}{\\textbf{Despesa prevista para o exercício de ", 
                      ANO_DOC, "}} \\\\\n")
  
  
  cabecalho = paste0("\\multicolumn{2}{c|}{\\textbf{UO}} & ",
                     "\\multicolumn{2}{c|}{ \\textbf{Programa}} & ",
                     "\\multicolumn{1}{C{2cm}}{ \\textbf{Crédito Inicial}} \\\\\n")

  cat(titulo1);  cat(titulo2)
  cat("\\specialrule{1.5pt}{2pt}{0pt}\n")
  cat(subtitulo)
  cat("\\specialrule{1pt}{0pt}{0pt}\n")
  cat(cabecalho)
  cat("\\hline\n")
  cat("\\endfirsthead\n")
 
  cat(titulo1);  cat(titulo2)
  cat("\\specialrule{1.5pt}{2pt}{0pt}\n")
  cat(subtitulo)
  cat("\\specialrule{1pt}{0pt}{0pt}\n")
  cat(cabecalho)
  cat("\\hline\n")
  cat("\\endhead\n")
  cat("\\endfoot\n")
  
  cat("\\hline\\hline\n")
  cat("\\endlastfoot\n")

  for(i in 1:nrow(banco)){


    linha = as.list(banco[i, ])

    if(linha[["PROGRAMA_DESC"]]=="TOTAL"){
      
      cat("\\hline\n")

      cat("\\multicolumn{4}{c|}{ \\textbf{", linha[["PROGRAMA_DESC"]],
          "}} & \\multicolumn{1}{R{2cm}}{ \\textbf{", linha[["VL_LOA_DESP"]], "}} \\\\\n", sep="")

      } else{

        cat("\\multicolumn{1}{C{1cm}|}{", linha[["UO_COD"]],
            "} & \\multicolumn{1}{L{1.5cm}|}{", linha[["UO_SIGLA"]],
            "} & \\multicolumn{1}{C{1cm}|}{", linha[["PROGRAMA_COD"]],
            "} & \\multicolumn{1}{L{10cm}|}{", linha[["PROGRAMA_DESC"]],
            "} & \\multicolumn{1}{R{2cm}}{", linha[["VL_LOA_DESP"]], "} \\\\\n", sep="")
      }
  }
  
  cat("\\hline\\hline\n")
  cat("\\end{longtable}\n")

  # NOTAS DE RODAPÉ
  
  cat("\\raggedright\n")
  cat("\\fontsize{7pt}{10pt}\\selectfont {FONTE: Armazém Sisor.} \\\\\n")
  cat("\\fontsize{7pt}{10pt}\\selectfont {ELABORAÇÃO: DCAF/SCPPO/SEPLAG}\\\\\n")
  cat("\\fontsize{7pt}{10pt}\\selectfont {Nota: Na elaboração desse relatório foram consideradas as fontes de recurso ", 
      banco[1, FONTE_EXEC], ".}\\\\\n", sep="")
  
  # FIM TABELA

@


\end{document}
