\documentclass{article}
\input{load_bibliotecas}

\begin{document}
\SweaveOpts{concordance=TRUE}
\pagestyle{empty}
\newgeometry{bottom=2cm,top=2cm,left=1.5cm,right=1.5cm}

<<results=tex,echo=FALSE>>=
  
  dir_loa = gsub("(.+LOA).*", "\\1", getwd())
  dir_data = paste0(dir_loa, "/volume1/data")
  
  ANO_DOC = as.numeric(readLines(paste0(dir_loa, "/utils/ano.txt"), warn = F))
  
  source(paste0(dir_loa, "/utils/funcoes.R"), encoding = "UTF-8")

  # INICIO TABELA 

  banco = ler_banco_txt(paste0(dir_data, "/T2_DCGF_DEMONSTRATIVO_RECEITA_CORRENTE_FISCAL.txt"))

  cat("\\renewcommand*{\\arraystretch}{1.9}\n")
  cat("\\footnotesize\n")
  cat("\\color{myblack}\n")
  cat("\\centering\n")

  cat("\\noindent\\begin{longtable}[c]{m{15cm}m{5cm}}\n")

  titulo1= paste0("\\multicolumn{2}{c}{\\cellcolor{gray!50} \\textcolor{myblack} {\\small \\textbf{",
                  "DEMONSTRATIVO DA RECEITA CORRENTE FISCAL}}} \\\\\n")
  
  titulo2= paste0("\\multicolumn{2}{c}{\\cellcolor{gray!50} \\textcolor{myblack} {\\footnotesize ",
                  "\\textbf{",
                  base_legal("T2_DCGF_DEMONSTRATIVO_RECEITA_CORRENTE_FISCAL"),
                  "}}}  \\\\\n")
  
 
  subtitulo = paste("\\multicolumn{1}{l}{\\textbf{Exercício: ", ANO_DOC,
                     "}} & \\multicolumn{1}{r}{\\textbf{R\\$1,00}} \\\\\n")
  
  cabecalho = paste("\\multicolumn{1}{l}{\\textbf{ ESPECIFICAÇÃO}} & \\multicolumn{1}{r}{VALOR} \\\\\n")
 
  cat(titulo1)
  cat(titulo2)
  cat(subtitulo)
  cat("\\hline\\hline\n")
  cat(cabecalho)
  cat("\\hline\\hline\n")
 
  for(i in 1:nrow(banco)){

    if(banco[i, espec]=="RECEITA CORRENTE FISCAL"){
      
      cat("\\hline\\hline\\hline\n")
      
      cat("\\multicolumn{1}{L{15cm}}{ \\textbf{", banco[i, negativoContabil(espec)],
          "}} & \\multicolumn{1}{r}{ \\textbf{", banco[i, negativoContabil(valor)], "}} \\\\\n")
    
      cat("\\hline\\hline\\hline\n")
      
      } else{

      cat("\\multicolumn{1}{L{15cm}}{", banco[i, negativoContabil(espec)],
          "} & \\multicolumn{1}{r}{", banco[i, negativoContabil(valor)], "} \\\\\n")
    
      }
  }

  cat("\\end{longtable}\n")

  cat("\\raggedright\n")
  cat("\\fontsize{7pt}{10pt}\\selectfont {FONTE: Armazém SISOR.}\\\\\n")
  cat("\\fontsize{7pt}{10pt}\\selectfont {ELABORAÇÃO: DCAF/SCPPO/SEPLAG}\\\\\n")
  
  # FIM TABELA

@

\end{document}
