\documentclass{article}

\input{load_bibliotecas}

\begin{document}
\SweaveOpts{concordance=TRUE}

\color{myblack}
\centering
 
% Geometry de acordo com apenas essa tabela

\pagestyle{empty} % Numeração da páginas não será feito aqui
\newgeometry{bottom=2cm,top=2cm,left=1.5cm,right=1.5cm}


<<results=tex, echo=FALSE>>=

  dir_loa = gsub("(.+LOA).*", "\\1", getwd())
  dir_latex = paste0(dir_loa, "/volume1/Rnw")
  dir_codigosR = paste0(dir_latex, "/CodigosR")
  dir_utils = paste0(dir_loa, "/utils/")
  dir_data = paste0(dir_loa, "/volume1/data")
  dir_bancos = paste0(dir_loa, "/bancos")

  ANO_DOC = as.numeric(readLines(paste(dir_utils, "/ano.txt", sep=""), warn = F))
  
  source(paste0(dir_utils, "funcoes.R"), encoding = "UTF-8")

  # INICIO TABELA
  library(dplyr)
  library(readr)
  
  banco = read_delim(
    file = paste0(dir_data, "/T30_INVESTIMENTOS_SEGUNDO_FUNCOES.txt"),
    delim = '\t', 
    locale = locale(encoding = 'Latin1', decimal_mark = ',', grouping_mark = '.'),
    na = '',
    col_types = cols(.default = col_character())
    ) %>% as.data.table()
  
  cat("\\renewcommand*{\\arraystretch}{1.7}\n")
  cat("\\normalsize\n")

  cat("\\noindent\\begin{longtable}[c]{m{8cm}|m{4cm}|m{5cm}}\n")
            
  titulo1 = paste0("\\multicolumn{3}{c}{\\cellcolor{gray!50} \\textcolor{myblack} {\\normalsize \\textbf{",
                  "INVESTIMENTOS SEGUNDO AS FUNÇÕES}}} \\\\\n")
  
  titulo2 = paste0("\\multicolumn{3}{c}{\\cellcolor{gray!50} \\textcolor{myblack} {\\footnotesize \\textbf{",
                  "(Art. 2\\degree, \\S 1\\degree, Inciso I da Lei 4.320/64)}}} \\\\\n")
 
  subtitulo = paste("\\multicolumn{2}{l}{\\textbf{Exercício: \\textcolor{myblack}{", ANO_DOC,
                    "}}} & \\multicolumn{1}{r}{R\\$1,00} \\\\[2ex] \n") 
  
  cabecalho = paste("\\multicolumn{1}{@{\\hspace{1em}}L{6cm}@{\\hspace{0.5em}}|}{\\textbf{ ESPECIFICAÇÃO}}  &",
                    "\\multicolumn{1}{c|}{\\textbf{ VALOR}} &",
                    "\\multicolumn{1}{c}{\\textbf{ \\% DE PARTICIPAÇÃO}} \\\\\n")
  
  cat(titulo1)
  cat(titulo2)
  cat("\\specialrule{1.5pt}{2pt}{0pt}\n")
  cat(subtitulo)
  cat("\\specialrule{1pt}{0pt}{0pt}\n")
  cat(cabecalho)
  cat("\\hline\n")
  cat("\\endfirsthead\n")

  cat(titulo1)
  cat(titulo2)
  cat("\\specialrule{1.5pt}{2pt}{0pt}\n")
  cat(subtitulo)
  cat("\\specialrule{1pt}{0pt}{0pt}\n")
  cat(cabecalho)
  cat("\\hline\n")
  cat("\\endhead\n")
  
  cat("\\endfoot\n")
  cat("\\hline\n")
  
  cat("\\hline\\hline\n") 
  cat("\\endlastfoot\n")
  
      for(i in 1:nrow(banco)){
        if(toupper(banco[i, especificacao])=="TOTAL"){
         
         cat("\\hline \\hline \n")
         
          cat("\\multicolumn{1}{@{\\hspace{1em}}L{8cm}|}{ \\textbf{", banco[i, especificacao], 
             "}} & \\multicolumn{1}{r|}{ \\textbf{", banco[i, valor], 
             "}} & \\multicolumn{1}{r}{ \\textbf{", 
             gsub("\\.", ",", banco[i, porcent]), 
             "}} \\\\\n")
         
       } else {
         
         cat("\\multicolumn{1}{@{\\hspace{1em}}L{8cm}|}{ ", banco[i, especificacao], 
             "} & \\multicolumn{1}{r|}{ ", banco[i, valor], 
             "} & \\multicolumn{1}{r}{ ", gsub("\\.", ",", banco[i, porcent]), "} \\\\\n")
         
       }
      }
  
  cat("\\end{longtable}\n")
  
  # FIM TABELA
  
  cat("\\newpage\n")

@

\end{document}
