\documentclass{article}

\input{load_bibliotecas}

\begin{document}
\SweaveOpts{concordance=TRUE}

\color{myblack}
\centering
 
% Geometry de acordo com apenas essa tabela

\pagestyle{empty} % Numeração da páginas não será feito aqui
\newgeometry{bottom=1.5cm,top=1cm,left=1.5cm,right=1.5cm}


<<results=tex, echo=FALSE>>=

  dir_loa = gsub("(.+LOA).*", "\\1", getwd())
  dir_latex = paste0(dir_loa, "/volume1/Rnw")
  dir_codigosR = paste0(dir_latex, "/CodigosR")
  dir_utils = paste0(dir_loa, "/utils/")
  dir_data3 = paste0(dir_loa, "/volume3/data/consolidado")
  dir_bancos = paste0(dir_loa, "/bancos")
  
  ANO_DOC = as.numeric(readLines(paste(dir_utils, "/ano.txt", sep=""), warn = F))
  
  source(paste0(dir_utils, "funcoes.R"), encoding = "UTF-8")

  # INICIO TABELA
  library(readr)
  
  banco = read_delim(
    file = paste0(dir_data3, 
                  "/T3_INVESTIMENTOS_SEGUNDO_FUNCOES_SUB_PROGRAMAS_PROJETOS_ATIVIDADES.txt"),
    delim = '\t', 
    locale = locale('pt', decimal_mark = ',', grouping_mark = '.'),
    na = '',
    col_types = cols(
                  codigo = col_character(),
                  especificacao = col_character(),
                  projeto = col_character(),
                  atividade = col_character(),
                  total = col_number()
                )
    )

  banco = as.data.table(banco)

  banco$total = format(banco$total, big.mark = '.', decimal.mark = ',', scientific = F)
  
  cat("\\renewcommand*{\\arraystretch}{1.7}\n")
  cat("\\scriptsize\n")

  cat("\\noindent\\begin{longtable}[c]{L{3cm}|m{6cm}|m{2cm}|m{2cm}|m{2cm}}\n")
            
  titulo1 = paste0("\\multicolumn{5}{c}{\\cellcolor{gray!50} \\textcolor{myblack} {\\normalsize \\textbf{",
                   "INVESTIMENTOS SEGUNDO FUNÇÕES, SUBFUNÇÕES E PROGRAMAS}}} \\\\\n")
  
  titulo2 = paste0("\\multicolumn{5}{c}{\\cellcolor{gray!50} \\textcolor{myblack}{\\normalsize \\textbf{",
                   "POR PROJETOS E ATIVIDADES}}} \\\\\n")
  
  titulo3 = paste0("\\multicolumn{5}{c}{\\cellcolor{gray!50} \\textcolor{myblack}{\\footnotesize \\textbf{",
                   "(Art. 32 da Lei 24.218/2022 - LDO)}}} \\\\\n")
  
  subtitulo1 = paste("\\multicolumn{4}{l}{\\textbf{Exercício: \\textcolor{myblack}{", ANO_DOC,
                    "}}} & \\multicolumn{1}{r}{R\\$1,00} \\\\[2ex] \n") 
  
  subtitulo2 = "\\multicolumn{5}{c}{ \\textbf{FUNÇÕES, SUBFUNÇÕES E PROGRAMAS}} \\\\\n"
  
  cabecalho = paste("\\multicolumn{1}{C{3cm}|}{\\textbf{ CÓDIGO}} & ",
                    "\\multicolumn{1}{@{\\hspace{1em}}L{6cm}@{\\hspace{0.5em}}|}{\\textbf{ ESPECIFICAÇÃO}}  &  ",
                    "\\multicolumn{1}{C{2cm}|}{\\textbf{ PROJETO}} &",
                    "\\multicolumn{1}{C{2cm}|}{\\textbf{ ATIVIDADE}} & ",
                    "\\multicolumn{1}{C{2cm}}{\\textbf{ TOTAL}} \\\\\n")
  
  cat(titulo1)
  cat(titulo2)
  cat(titulo3)
  cat("\\specialrule{1.5pt}{2pt}{0pt}\n")
  cat(subtitulo1)
  cat(subtitulo2)
  cat("\\specialrule{1pt}{0pt}{0pt}\n")
  cat(cabecalho)
  cat("\\hline\n")
  cat("\\endfirsthead\n")

  cat(titulo1)
  cat(titulo2)
  cat(titulo3)
  cat("\\specialrule{1.5pt}{2pt}{0pt}\n")
  cat(subtitulo1)
  cat(subtitulo2)
  cat("\\specialrule{1pt}{0pt}{0pt}\n")
  cat(cabecalho)
  cat("\\hline\n")
  cat("\\endhead\n")
  
  cat("\\endfoot\n")
  
  cat("\\hline\n")
  
  cat("\\hline\\hline\n") 
  cat("\\endlastfoot\n")
  
     for(i in 1:nrow(banco)){
       if(grepl("TOTAL", banco[i, especificacao], ignore.case = T)){
         
         cat("\\hline \\hline \n")
         
         cat("\\multicolumn{2}{@{\\hspace{1em}}L{6cm}@{\\hspace{0.5em}}|}{ \\textbf{", banco[i, especificacao], 
             "}} & \\multicolumn{1}{r@{\\hspace{0.5em}}|}{ \\textbf{", banco[i, projeto], 
             "}} & \\multicolumn{1}{r@{\\hspace{0.5em}}|}{ \\textbf{",   banco[i, atividade],
             "}} & \\multicolumn{1}{r@{\\hspace{1em}}}{ \\textbf{", banco[i, total], "}} \\\\\n") 
         
       } else if(grepl("\\d+(\\.0{3}){2}", as.character(banco[i, codigo]))){
         
         cat("\\multicolumn{1}{L{3cm}|}{\\textbf{ ",TratamentoNA(banco[i, codigo]), 
             "}} & \\multicolumn{1}{@{\\hspace{1em}}L{6cm}@{\\hspace{0.5em}}|}{ \\textbf{", banco[i, especificacao], 
             "}} & \\multicolumn{1}{r@{\\hspace{0.5em}}|}{ \\textbf{", banco[i, projeto], 
             "}} & \\multicolumn{1}{r@{\\hspace{0.5em}}|}{ \\textbf{",   banco[i, atividade],
             "}} & \\multicolumn{1}{r@{\\hspace{1em}}}{ \\textbf{", banco[i, total], "}} \\\\\n")
         
       } else if(grepl("\\d+\\.[1-9]{1}\\d{2}\\.0{3}", as.character(banco[i, codigo]))){
         
         cat("\\multicolumn{1}{L{3cm}|}{ \\hspace{1em} \\textbf{",TratamentoNA(banco[i, codigo]), 
             "}} & \\multicolumn{1}{@{\\hspace{2em}}L{6cm}@{\\hspace{0.5em}}|}{ \\textbf{",  banco[i, especificacao], 
             "}} & \\multicolumn{1}{r@{\\hspace{0.5em}}|}{ \\textbf{", banco[i, projeto], 
             "}} & \\multicolumn{1}{r@{\\hspace{0.5em}}|}{ \\textbf{",   banco[i, atividade],
             "}} & \\multicolumn{1}{r@{\\hspace{1em}}}{ \\textbf{", banco[i, total], "}} \\\\\n")
         
       } else{
         
         cat("\\multicolumn{1}{L{3cm}|}{ \\hspace{2em}",TratamentoNA(banco[i, codigo]), 
             "} & \\multicolumn{1}{@{\\hspace{3em}}L{6cm}@{\\hspace{0.5em}}|}{ ", banco[i, especificacao], 
              "} & \\multicolumn{1}{r@{\\hspace{0.5em}}|}{ ", banco[i, projeto], 
             "} & \\multicolumn{1}{r@{\\hspace{0.5em}}|}{ ",   banco[i, atividade],
             "} & \\multicolumn{1}{r@{\\hspace{1em}}}{ ", banco[i, total], "} \\\\\n")
         
       }
     }
  

  cat("\\end{longtable}\n")
  
  # FIM TABELA
  
  cat("\\newpage\n")

@


\end{document}
