\documentclass{article}

\input{load_bibliotecas}

\begin{document}
\SweaveOpts{concordance=TRUE}

\scriptsize

\renewcommand*{\arraystretch}{1.9}
 
\color{myblack}
\centering
 
\newgeometry{bottom=1cm,top=1cm,left=1.5cm,right=1.5cm}
\thispagestyle{empty}

<<echo=F, results=tex>>=

  dir_loa = gsub("(.+LOA).*", "\\1", getwd())
  dir_latex = paste0(dir_loa, "/volume1/Rnw")
  dir_codigosR = paste0(dir_latex, "/CodigosR")
  dir_utils = paste0(dir_loa, "/utils/")
  dir_data3 = paste0(dir_loa, "/volume3/data/consolidado")
  dir_bancos = paste0(dir_loa, "/bancos")
  
  ANO_DOC = as.numeric(readLines(paste(dir_utils, "/ano.txt", sep=""), warn = F))
  
  source(paste0(dir_utils, "funcoes.R"), encoding = "UTF-8")

  # INICIO TABELA

  t1_geral = data.table(read.table(paste0(dir_data3, "/T1_INVESTIMENTO_POR_EMPRESA.txt"),
                                   header=T, sep="\t", dec=",", stringsAsFactors = FALSE))

  titulo1 = paste0("\\multicolumn{7}{c}{\\cellcolor{gray!50} \\textcolor{myblack} {\\normalsize \\textbf{",
                   "INVESTIMENTOS POR EMPRESA SEGUNDO FONTES DE RECURSO}}}\\TBstrut  \\\\[2ex]\n")

  titulo2 = paste0("\\multicolumn{7}{c}{\\cellcolor{gray!50} \\textcolor{myblack} {\\normalsize \\textbf{",
                   base_legal("T32_INVESTIMENTOS_POR_EMPRESA_SEGUNDO_FONTES_RECURSO"),
                   "}}} \\\\\n")
 
  subtitulo = paste("\\multicolumn{3}{l}{\\textbf{Exercício: \\textcolor{myblack}{", ANO_DOC, 
                    "}}} & \\multicolumn{4}{r}{R\\$1,00} \\\\\n")

  cabecalho1= paste0("\\multirow{2}{*}{\\parbox{5cm}{\\centering \\textbf{ÓRGÃOS E ENTIDADES}}} & ",
                     "\\multicolumn{3}{|c|}{\\textbf{AUMENTO DE CAPITAL}} & ",
                     "\\multicolumn{2}{c|}{\\textbf{OUTROS}} & ",
                     "\\multicolumn{1}{c}{\\multirow{2}{*}{\\textbf{TOTAL}}} \\\\\n")

  cabecalho2= paste0(" & \\centering{ \\textbf{ TESOURO ORDINÁRIO}} & ",
                     "\\centering{ \\textbf{ TESOURO VINCULADO}} &  ",
                     "\\centering{ \\textbf{ OUTRAS ENTIDADES}} & ",
                     "\\centering{ \\textbf{ OPERAÇÃO DE CRÉDITO}} & ",
                     "\\centering{ \\textbf{ RECURSOS PRÓPRIOS}} & \\\\\n")

  cat("\\footnotesize\n")
  cat("\\noindent\\begin{longtable}[c]{m{5cm}|m{2cm}|m{2cm}|m{2cm}|m{2cm}|m{2cm}|m{2cm}}\n")

  cat(titulo1)
  cat(titulo2)
  cat("\\specialrule{1.5pt}{2pt}{0pt}\n")
  cat(subtitulo)
  cat("\\specialrule{1pt}{0pt}{0pt}\n")
  cat(cabecalho1)
  cat("\\cline{2-6}\n")
  cat(cabecalho2)
 
  cat("\\hline\n")
  cat("\\endfirsthead\n")

  cat(titulo1)
  cat(titulo2)
  cat("\\specialrule{1.5pt}{2pt}{0pt}\n")
  cat(subtitulo)
  cat("\\specialrule{1pt}{0pt}{0pt}\n")
  cat(cabecalho1)
  cat("\\cline{2-6}\n")
  cat(cabecalho2)
 
  cat("\\hline\n")
  cat("\\endhead\n")

  cat("\\endfoot\n")

  cat("\\hline\n")

  cat("\\hline\\hline\n")
  cat("\\endlastfoot\n")


  for(i in 1:nrow(t1_geral)){
    if(toupper(t1_geral[i, orgaos])=="TOTAL"){
    
    cat("\\hline \\hline\n")
    
    cat("\\multicolumn{1}{L{5cm}|}{ \\textbf{", t1_geral[i, orgaos], 
        "}} & \\multicolumn{1}{r|}{ \\textbf{", t1_geral[i, ordinario], 
        "}} & \\multicolumn{1}{r|}{ \\textbf{", t1_geral[i, vinculado], 
        "}} & \\multicolumn{1}{r|}{ \\textbf{", t1_geral[i, outras],
        "}} & \\multicolumn{1}{r|}{ \\textbf{", t1_geral[i, operacoes],
        "}} & \\multicolumn{1}{r|}{ \\textbf{", t1_geral[i, recursos],
        "}} & \\multicolumn{1}{r}{ \\textbf{", t1_geral[i, total],"}} \\\\\n", sep="")
    
    } else{
  
      cat("\\multicolumn{1}{L{5cm}|}{", t1_geral[i, orgaos],
          "} & \\multicolumn{1}{r|}{", t1_geral[i, ordinario], 
          "} & \\multicolumn{1}{r|}{", t1_geral[i, vinculado],
          "} & \\multicolumn{1}{r|}{", t1_geral[i, outras], 
          "} & \\multicolumn{1}{r|}{", t1_geral[i, operacoes],
          "} & \\multicolumn{1}{r|}{", t1_geral[i, recursos], 
          "} & \\multicolumn{1}{r}{ \\textbf{", t1_geral[i, total],"}} \\\\\n", sep="")
  }
}

cat("\\end{longtable}\n")

# FIM TABELA

@

\end{document}