\documentclass{article}
\input{load_bibliotecas}

\begin{document}
\SweaveOpts{concordance=TRUE}

\pagestyle{empty}
\newgeometry{bottom=1.5cm,top=1.5cm,left=1.5cm,right=1.5cm}


<<results=tex,echo=FALSE>>=
  
  dir_loa = gsub("(.+LOA).*", "\\1", getwd())
  dir_data = paste0(dir_loa, "/volume1/data")
  ANO_DOC = as.numeric(readLines(paste0(dir_loa, "/utils/ano.txt"), warn = F))
  source(paste0(dir_loa, "/utils/funcoes.R"), encoding = "UTF-8")

  # INICIO TABELA 

  banco = ler_banco_txt(paste0(dir_data, "/T37_DCGF_DEMONSTRATIVOS_RECURSOS_APLICADOS_SEGURANCA_ALIMENTAR_NUTRICIONAL.txt"))
  
  cat("\\renewcommand*{\\arraystretch}{1.9}\n")
  cat("\\scriptsize\n")
  cat("\\color{myblack}\n")
  cat("\\centering\n")

  cat("\\noindent\\begin{longtable}[c]{m{3cm}|m{12cm}|m{2cm}}\n", sep="")

  titulo1= paste0("\\multicolumn{3}{c}{\\cellcolor{gray!50} \\textcolor{myblack} {\\footnotesize ",
                  "\\textbf{DEMONSTRATIVOS DE RECURSOS A SEREM APLICADOS DIRETA OU INDIRETAMENTE NA EXECUÇÃO DA}}} \\\\\n")
  
  titulo2= paste0("\\multicolumn{3}{c}{\\cellcolor{gray!50} \\textcolor{myblack} {\\footnotesize ",
                  "\\textbf{POLÍTICA ESTADUAL DE SEGURANÇA ALIMENTAR E NUTRICIONAL SUSTENTÁVEL}}} \\\\\n")
  
  titulo3= paste("\\multicolumn{3}{c}{\\cellcolor{gray!50} \\textcolor{myblack} {\\scriptsize",
                 "\\textbf{(Art. 7\\degree, Inciso XVII da Lei 24.218/2022 - LDO)}}}  \\\\\n")
 
  subtitulo = paste("\\multicolumn{2}{l}{\\textbf{Exercício: ",
                     ANO_DOC , "}} & \\multicolumn{1}{r}{\\textbf{R\\$1,00}} \\\\\n")
 
  cabecalho = paste0("\\multicolumn{1}{C{2cm}|}{ \\footnotesize{ \\textbf{ Funcional Programática}}} & ",
                     "\\multicolumn{1}{C{12cm}|}{ \\textbf{ \\footnotesize{Ação}}} &",
                     "\\multicolumn{1}{C{2cm}}{ \\textbf{ \\footnotesize{Valor}}} \\\\\n")

  cat(titulo1)
  cat(titulo2)
  cat(titulo3)
  cat("\\specialrule{1.5pt}{2pt}{0pt}\n")
  cat(subtitulo)
  cat("\\specialrule{1pt}{0pt}{0pt}\n")
  cat(cabecalho)
  cat("\\hline \\hline\n")
  cat("\\endfirsthead\n")
  
  cat(titulo1)
  cat(titulo2)
  cat(titulo3)
  cat("\\specialrule{1.5pt}{2pt}{0pt}\n")
  cat(subtitulo)
  cat("\\specialrule{1pt}{0pt}{0pt}\n")
  cat(cabecalho)
  cat("\\hline \\hline\n")
  cat("\\endhead\n")
  
  cat("\\endfoot\n")
  cat("\\hline\n")
  cat("\\hline\\hline\n") 
  cat("\\endlastfoot\n")
  
  for(i in 1:nrow(banco)){

    linha = as.list(banco[i, ])

    if(linha[["FUNCIONAL"]]=="TOTAL"){
      
      cat("\\hline\\hline\n")

      cat("\\multicolumn{2}{c|}{ \\textbf{", linha[["FUNCIONAL"]],
          "}} & \\multicolumn{1}{R{2cm}}{ \\textbf{", linha[["VL_DESP"]],
          "}} \\\\\n", sep="")

      } else{

        cat("\\multicolumn{1}{C{3cm}|}{", linha[["FUNCIONAL"]], 
            "} & \\multicolumn{1}{L{12cm}|}{", linha[["ACAO_DESC"]],
            "} & \\multicolumn{1}{R{2cm}}{", linha[["VL_DESP"]],
            "} \\\\\n", sep="")
        
      }
  }
  
  cat("\\hline\\hline\n")
  cat("\\end{longtable}\n")

  # NOTAS DE RODAPÉ
  
  # cat("\\raggedright\n")
  # 
  # cat("\\fontsize{8pt}{10pt}\\selectfont {NOTA:} \\\\\n")
  # cat("\\fontsize{8pt}{10pt}\\selectfont {As ações foram selecionadas de acordo com critério estabelecidos pela",
  #     "Lei estadual 15.982 de 19/01/2006, que dispõe sobre a Política Estadual de Segurança Alimentar e Nutricional",
  #     "Sustentável e dá outras providencias. O demonstrativo apresenta ações previstas para 2018 que apresentam",
  #     "relação direta ou indiretamente com a Política Estadual de Segurança Alimentar e Nutricional Sustentável.} \\\\\n")
  
  
  # FIM TABELA

@

\end{document}
