\documentclass{article}
\input{load_bibliotecas}

\begin{document}
\SweaveOpts{concordance=TRUE}

\pagestyle{empty}
\newgeometry{bottom=1.5cm,top=1.2cm,left=1.2cm,right=1.5cm}


<<results=tex,echo=FALSE>>=
  
  dir_loa = gsub("(.+LOA).*", "\\1", getwd())
  dir_data = paste0(dir_loa, "/volume1/data")
  ANO_DOC = as.numeric(readLines(paste0(dir_loa, "/utils/ano.txt"), warn = F))
  source(paste0(dir_loa, "/utils/funcoes.R"), encoding = "UTF-8")

  # INICIO TABELA 

  banco = ler_banco_txt(paste0(dir_data, 
                               "/T38_DCGF_DEMONSTRATIVO_RECEITAS_DESPESAS_PREVIDENCIARIAS_RPPS.txt"))

  cat("\\renewcommand*{\\arraystretch}{1.4}\n")
  cat("\\footnotesize\n")
  cat("\\color{myblack}\n")
  cat("\\centering\n")

  cat("\\noindent\\begin{longtable}[c]{m{12cm}m{3cm}}\n", sep="")

  titulo1= paste0("\\multicolumn{2}{c}{\\cellcolor{gray!50} \\textcolor{myblack} {\\footnotesize ",
                  "\\textbf{DEMONSTRATIVO DAS RECEITAS E DESPESAS PREVIDENCIÁRIAS}}} \\\\\n")
  
  titulo2= paste0("\\multicolumn{2}{c}{\\cellcolor{gray!50} \\textcolor{myblack}{ ",
                  "\\textbf{(Art. 7\\degree, Inciso XI da Lei 24.218/2022 - LDO)}}} \\\\\n")
 
  subtitulo = paste("\\multicolumn{1}{l}{\\textbf{Exercício: \\textcolor{myblack}{ ",
                     ANO_DOC , "}}} & \\multicolumn{1}{r}{\\textbf{R\\$1,00}} \\\\\n")
 
  cabecalho = paste0("\\multicolumn{1}{L{12cm}}{ \\textbf{ESPECIFICAÇÃO}} & ",
                     "\\multicolumn{1}{C{3cm}}{ \\textbf{VALOR}} \\\\\n")
                     
  cat(titulo1)
  cat(titulo2)
  cat("\\specialrule{1.5pt}{2pt}{0pt}\n")
  cat(subtitulo)
  cat("\\specialrule{1pt}{0pt}{0pt}\n")
  cat(cabecalho)
  cat("\\hline\n")
  cat("\\endfirsthead\n")
 
  cat(titulo1)
  cat(titulo2)
  cat("\\specialrule{1.5pt}{2pt}{0pt}\n")
  cat(subtitulo)
  cat("\\specialrule{1pt}{0pt}{0pt}\n")
  cat(cabecalho)
  cat("\\hline\n")
  cat("\\endhead\n")
  cat("\\endfoot\n")
  
  cat("\\hline\\hline\n")
  cat("\\endlastfoot\n")

  for(i in 1:nrow(banco)){

    linha = as.list(banco[i, ])
    colocarNegrito = 0
    
    if(linha[["nvl"]] %in% c(0)){ 
      colocarNegrito = 1
      cat("\\hline\\hline\n")
      
    }
      
      recuo_h = 2*as.numeric(linha[["nvl"]]) # Recuo Horizontal

      cat("\\multicolumn{1}{L{12cm}}{\\hspace{", 
          recuo_h,
          "em} ", 
          aplicaNegrito(linha[["espec"]], colocarNegrito),
          "} & \\multicolumn{1}{R{3cm}}{", 
          aplicaNegrito(linha[["VL_LOA"]], colocarNegrito),
          "} \\\\\n", 
          sep="")

      
     #if(linha[["nvl"]] %in% c(0)) cat("\\hline\\hline\n")
      
    
  }
  
  cat("\\hline\\hline\n")
  cat("\\end{longtable}\n")

  # NOTAS DE RODAPÉ
  
  cat("\\raggedright\n")
  cat("\\fontsize{7pt}{10pt}\\selectfont {FONTE: Armazém Sisor.} \\\\\n")
  cat("\\fontsize{7pt}{10pt}\\selectfont {ELABORAÇÃO: DCAF/SCPPO/SEPLAG}\\\\\n")
  
  # FIM TABELA

@

\end{document}
