\documentclass{article}

\input{load_bibliotecas}

\begin{document}
\SweaveOpts{concordance=TRUE}

\color{myblack}
\centering
 
% Geometry de acordo com apenas essa tabela

\pagestyle{empty} % Numeração da páginas não será feito aqui
\newgeometry{bottom=2cm,top=2cm,left=1.5cm,right=1.5cm}


<<results=tex, echo=FALSE>>=

  dir_loa = gsub("(.+LOA).*", "\\1", getwd())
  dir_latex = paste0(dir_loa, "/volume1/Rnw")
  dir_codigosR = paste0(dir_latex, "/CodigosR")
  dir_utils = paste0(dir_loa, "/utils/")
  dir_data = paste0(dir_loa, "/volume1/data")
  dir_bancos = paste0(dir_loa, "/bancos")

  ANO_DOC = as.numeric(readLines(paste(dir_utils, "/ano.txt", sep=""), warn = F))
  
  source(paste0(dir_utils, "funcoes.R"), encoding = "UTF-8")

  # INICIO TABELA
  suppressMessages(suppressWarnings(library(readr)))
  
  banco = read_delim(
    file = paste0(dir_data, "/T39_DCGF_DEMONSTRATIVO_CUMPRIMENTO_LIMITACAO_CRESCIMENTO_DESPESA.txt"),
    delim = '\t', 
    locale = locale('pt', decimal_mark = ',', grouping_mark = '.'),
    na = '', 
    col_types = cols(VL_EMP_2017 = col_character(),
                     VL_LIMITE = col_character(),
                     credito_inicial = col_character(),
                     excedente = col_character())
    )

  banco = as.data.table(banco)

  cat("\\renewcommand*{\\arraystretch}{1.7}\n")
  cat("\\normalsize\n")

  cat("\\noindent\\begin{longtable}[c]{m{5cm}|m{3cm}|m{3cm}|m{3cm}|m{3cm}}\n")
            
  titulo1 = paste0("\\multicolumn{5}{c}{\\cellcolor{gray!50} \\textcolor{myblack} {\\normalsize \\textbf{",
                  "DEMONSTRATIVO DO CUMPRIMENTO DA LIMITAÇÃO AO CRESCIMENTO DA DESPESA PÚBLICA}}} \\\\\n")
  
  titulo2 = paste0("\\multicolumn{5}{c}{\\cellcolor{gray!50} \\textcolor{myblack} {\\footnotesize \\textbf{",
                  "(Art. 4\\degree da Lei Complementar 156/2016)}}} \\\\\n")
 
  subtitulo1 = paste("\\multicolumn{5}{l}{\\textbf{ORÇAMENTO FISCAL}} \\\\\n") 
  
  subtitulo2 = paste("\\multicolumn{4}{l}{\\textbf{Exercício: \\textcolor{myblack}{", ANO_DOC,
                    "}}} & \\multicolumn{1}{r}{R\\$1,00} \\\\\n") 
  
  cabecalho = paste("\\multicolumn{1}{L{5cm}|}{\\textbf{PODER}}  &",
                    "\\multicolumn{1}{C{3cm}|}{\\textbf{Despesa Realizada 2017}} &",
                    "\\multicolumn{1}{C{3cm}|}{\\textbf{Limite para Despesa 2019}} &",
                    "\\multicolumn{1}{C{3cm}|}{\\textbf{Crédito Inicial 2019}} &",
                    "\\multicolumn{1}{C{3cm}}{\\textbf{Excedente}} \\\\\n")
  
  cat(titulo1)
  cat(titulo2)
  cat("\\specialrule{1.5pt}{2pt}{0pt}\n")
  cat(subtitulo1)
  cat(subtitulo2)
  cat("\\specialrule{1pt}{0pt}{0pt}\n")
  cat(cabecalho)
  cat("\\hline\n")
  cat("\\endfirsthead\n")

  cat(titulo1)
  cat(titulo2)
  cat("\\specialrule{1.5pt}{2pt}{0pt}\n")
  cat(subtitulo1)
  cat(subtitulo2)
  cat("\\specialrule{1pt}{0pt}{0pt}\n")
  cat(cabecalho)
  cat("\\hline\n")
  cat("\\endhead\n")
  
  cat("\\endfoot\n")
  cat("\\hline\n")
  
  cat("\\hline\\hline\n") 
  cat("\\endlastfoot\n")
  
      for(i in 1:nrow(banco)){
        if(toupper(banco[i, poder])=="TOTAL"){

         cat("\\hline \\hline \n")

          cat("\\multicolumn{1}{L{5cm}|}{ \\textbf{TOTAL ORÇAMENTO FISCAL",
              "}} & \\multicolumn{1}{r|}{ \\textbf{", banco[i, VL_EMP_2017],
              "}} & \\multicolumn{1}{r|}{ \\textbf{", banco[i, VL_LIMITE],
              "}} & \\multicolumn{1}{r|}{ \\textbf{", banco[i, credito_inicial],
              "}} & \\multicolumn{1}{r}{ \\textbf{", zero2traco(banco[i, excedente]), "}} \\\\\n")

       } else {

         cat("\\multicolumn{1}{L{5cm}|}{", banco[i, poder],
             "} & \\multicolumn{1}{r|}{", banco[i, VL_EMP_2017],
             "} & \\multicolumn{1}{r|}{", banco[i, VL_LIMITE],
             "} & \\multicolumn{1}{r|}{", banco[i, credito_inicial],
             "} & \\multicolumn{1}{r}{", zero2traco(banco[i, excedente]), "} \\\\\n")

       }
      }
  
  cat("\\end{longtable}\n")
  
  # Notas de rodapé
  cat("\\raggedright\n")
  cat("\\fontsize{9pt}{10pt}\\selectfont {FONTE: Armazém SIAFI.} \\\\\n")
  cat("\\vskip 0.2cm\n")
  cat("\\fontsize{9pt}{10pt}\\selectfont {ELABORAÇÃO: DCAF/SCPPO/SEPLAG}\\\\\n")
  cat("\\vskip 0.2cm\n")
  cat("\\fontsize{9pt}{10pt}\\selectfont {Nota: Na elaboração deste relatório foram consideradas ",
      "as estimativas de inflação previstas no Boletim Focus de 21/09/18, com projeção de IPCA de 4,28\\% ",
      "para 2018 e 4,18\\% para 2019.}\\\\\n", sep="")
  
  
  # FIM TABELA
  
  

@

\end{document}
