\documentclass{article}

\input{load_bibliotecas}

\begin{document}
\SweaveOpts{concordance=TRUE}

\color{myblack}
\centering
\pagestyle{empty}

\newgeometry{bottom=2cm,top=2cm,left=1.5cm,right=1.5cm}


<<results=tex, echo=FALSE>>=

  dir_loa = gsub("(.+LOA).*", "\\1", getwd())
  dir_latex = paste0(dir_loa, "/volume1/Rnw")
  dir_codigosR = paste0(dir_latex, "/CodigosR")
  dir_utils = paste0(dir_loa, "/utils/")
  dir_data = paste0(dir_loa, "/volume1/data")
  dir_bancos = paste0(dir_loa, "/bancos")

  ANO_DOC = as.numeric(readLines(paste(dir_utils, "/ano.txt", sep=""), warn = F))
  
  source(paste0(dir_utils, "funcoes.R"), encoding = "UTF-8")

  # INICIO TABELA
  library(dplyr)
  library(readr)
  
  banco = read_delim(
    file = paste0(dir_data, "/T5_DEMONSTRATIVO_CONSOLIDADO_CATEGORIA_PESSOAL.txt"),
    delim = '\t', 
    locale = locale('pt', encoding = 'Latin1', decimal_mark = ',', grouping_mark = '.'),
    na = '',
    col_types = cols(.default = col_character())
    ) %>% as.data.table()

  cat("\\renewcommand*{\\arraystretch}{1.7}\n")
  cat("\\footnotesize\n")

  cat("\\noindent\\begin{longtable}[c]{m{8cm}|m{2cm}|m{2cm}|m{2.5cm}|m{2cm}}\n")
            
  titulo1 = paste0("\\multicolumn{5}{c}{\\cellcolor{gray!50} \\textcolor{myblack} {\\normalsize \\textbf{",
                   "DEMONSTRATIVO CONSOLIDADO DA CATEGORIA DE PESSOAL POR UNIDADE ORÇAMENTÁRIA}}} \\\\\n")
  
  titulo2= paste0("\\multicolumn{5}{c}{\\cellcolor{gray!50} \\textcolor{myblack} {\\footnotesize ",
                  "\\textbf{(Art. 7\\degree, Inciso XXIII da Lei 24.218/2022 - LDO)}}}  \\\\\n")
  
  subtitulo = paste("\\multicolumn{5}{l}{\\textbf{Exercício: \\textcolor{myblack}{ ", 
                    ANO_DOC," }}} \\\\[2ex] \n") 
  
  cabecalho1= paste0("\\multirow{2}{*}{\\parbox{8cm}{\\centering \\textbf{ÓRGÃO/ENTIDADE}}} & ",
                    "\\multicolumn{4}{|c}{\\textbf{CATEGORIA PESSOAL}} \\\\\n")

  cabecalho2= paste(" & \\multicolumn{1}{|C{2cm}|}{\\textbf{ ATIVO}} &",
                    "\\multicolumn{1}{C{1.5cm}|}{\\textbf{ INATIVO}} &",
                    "\\multicolumn{1}{C{2.5cm}|}{\\textbf{ TERCEIRIZADO}} &",
                    "\\multicolumn{1}{C{2cm}}{\\textbf{ TOTAL}} \\\\\n")
  
  cat(titulo1)
  cat(titulo2)
  cat("\\specialrule{1.5pt}{2pt}{0pt}\n")
  cat(subtitulo)
  cat("\\specialrule{1pt}{0pt}{0pt}\n")
  cat(cabecalho1)
  cat("\\cline{2-5}\n")
  cat(cabecalho2)
  cat("\\hline\n")
  cat("\\endfirsthead\n")

  cat(titulo1)
  cat(titulo2)
  cat("\\specialrule{1.5pt}{2pt}{0pt}\n")
  cat(subtitulo)
  cat("\\specialrule{1pt}{0pt}{0pt}\n")
  cat(cabecalho1)
  cat("\\cline{2-5}\n")
  cat(cabecalho2)
  cat("\\hline\n")
  cat("\\endhead\n")
  
  cat("\\endfoot\n")
  
  cat("\\hline\n")
  
  cat("\\hline\\hline\n") 
  cat("\\endlastfoot\n")
  
     for(i in 1:nrow(banco)){
       
       if(toupper(banco[i, orgao])=="TOTAL"){
         
         cat("\\hline \\hline\n")
         
         cat("\\multicolumn{1}{L{8cm}@{\\hspace{0.5em}}|}{ \\textbf{", toupper(banco[i, orgao]), 
             "}} & \\multicolumn{1}{r@{\\hspace{0.5em}}|}{ \\textbf{", banco[i, ativo], 
             "}} & \\multicolumn{1}{r@{\\hspace{0.5em}}|}{ \\textbf{", banco[i, inativo],
             "}} & \\multicolumn{1}{r@{\\hspace{1em}}|}{ \\textbf{", banco[i, terceirizado], 
             "}} & \\multicolumn{1}{r@{\\hspace{1em}}}{ \\textbf{", banco[i, total], "}} \\\\\n")
       
         } else{

         cat("\\multicolumn{1}{L{8cm}@{\\hspace{0.5em}}|}{ ",banco[i, orgao], 
             "} & \\multicolumn{1}{r@{\\hspace{0.5em}}|}{ ", banco[i, ativo], 
             "} & \\multicolumn{1}{r@{\\hspace{0.5em}}|}{ ", banco[i, inativo],
             "} & \\multicolumn{1}{r@{\\hspace{1em}}|}{ ", banco[i, terceirizado], 
             "} & \\multicolumn{1}{r@{\\hspace{1em}}}{ ", banco[i, total], "} \\\\\n")

       }
     }
  

  cat("\\end{longtable}\n")
  
  # FIM TABELA
  
  cat("\\newpage\n")

@

\end{document}
