\documentclass{article}

\input{load_bibliotecas}
\renewcommand{\contentsname}{Sumário}

\begin{document}
\SweaveOpts{concordance=TRUE}

<<ParametrosRecortes, echo=FALSE, results=hide>>=
  dir_loa = gsub("(.+LOA).*", "\\1", getwd())
  dir_latex = paste0(dir_loa, "/volume3/Rnw")
  dir_codigosR = paste0(dir_latex, "/CodigosR")
  dir_utils = paste0(dir_loa, "/utils/")
  dir_data = paste0(dir_loa, "/volume3/data")
  dir_bancos = paste0(dir_loa, "/bancos")

  ANO_DOC = as.numeric(readLines(paste(dir_utils, "/ano.txt", sep=""), warn = F))
  ETAPA_ORCAMENTO = readLines(paste(dir_utils, "etapa_orcamento.txt", sep=""), warn = F)
  
  source(paste0(dir_utils, "funcoes.R"), encoding = "UTF-8")
  source(paste0(dir_utils, "formataTexto.R"), encoding = "UTF-8")

  getCodigoR(paste0(dir_latex, "/T1_INVESTIMENTOS_POR_EMPRESA_SEGUNDO_FONTES_DE_RECURSO.Rnw"), dir_codigosR)
  getCodigoR(paste0(dir_latex, "/T2_INVESTIMENTOS_EMPRESA_SEGUNDO_DETALHAMENTO_INVESTIMENTOS.Rnw"), dir_codigosR)
  getCodigoR(paste0(dir_latex, "/T3_INVESTIMENTOS_SEGUNDO_FUNCOES_SUB_PROGRAMAS_PROJETOS_ATIVIDADES.Rnw"), dir_codigosR)
  getCodigoR(paste0(dir_latex, "/T1_relatorio_por_empresa.Rnw"), dir_codigosR)
  getCodigoR(paste0(dir_latex, "/T2_ORIGENS_RECURSOS_INVESTIMENTOS.Rnw"), dir_codigosR)
  getCodigoR(paste0(dir_latex, "/T3_RECURSOS_FINANCEIROS_FONTE_RECURSOS_APLICACAO_INVESTIMENTO.Rnw"), dir_codigosR)
  getCodigoR(paste0(dir_latex, "/T4_DETALHAMENTO_INVESTIMENTOS.Rnw"), dir_codigosR)
  getCodigoR(paste0(dir_latex, "/T5_QUADRO_DETALHAMENTO_INVESTIMENTO.Rnw"), dir_codigosR)
  getCodigoR(paste0(dir_latex, "/ANEXO_ORIGEM_DE_RECURSOS_PARA_INVESTIMENTO.Rnw"), dir_codigosR)
  getCodigoR(paste0(dir_latex, "/ANEXO_DETALHAMENTO_INVESTIMENTOS.Rnw"), dir_codigosR)

@


% Capa
\begin{titlepage}
\newgeometry{top=0cm, right=0cm, left=-6cm, bottom=0cm}
\includepdf[pages={6}]{capaLOA.pdf}
\end{titlepage}
% \capa

% Títulos
% Pagina com os titulos
\restoregeometry
\newgeometry{top=1cm}
\thispagestyle{empty}
\begin{figure}[h]
\begin{center}
\includegraphics[width=2cm, height=2cm]{brasao_mg}
\end{center}
\end{figure}
\vspace*{-2em}
\begin{center}
\large
Governo do Estado de Minas Gerais \\
Secretaria de Estado de Planejamento e Gestão \\
Subsecretaria de Planejamento e Orçamento \\
Superintendência Central de Planejamento e Orçamento

\vspace*{10em}
 \fontsize{45pt}{10pt}\selectfont {\textbf{\Sexpr{ETAPA_ORCAMENTO} \Sexpr{ANO_DOC}}}

\vspace*{5em}
\fontsize{15pt}{12pt}\selectfont {\textbf{ANEXO III}} \\
\large{ORÇAMENTO DE INVESTIMENTO DAS EMPRESAS CONTROLADAS PELO ESTADO}

\end{center}
%\end{pagestyle}

\afterpage{\null\thispagestyle{empty}\newpage}
\newpage
% \Titulos

% Sumario
\restoregeometry
\small
\tableofcontents
\newpage
\phantomsection
% \Sumario

% Pagina iniciando Quadros Consolidados
\ifthispageodd{ }{\afterpage{\null\thispagestyle{empty}\newpage}}
\restoregeometry
\vspace*{9cm}
\addcontentsline{toc}{section}{ QUADROS CONSOLIDADOS}
\centering \Huge {\textbf{QUADROS CONSOLIDADOS}}
\newpage
\phantomsection
\afterpage{\null\thispagestyle{empty}\newpage}
\scriptsize

\renewcommand*{\arraystretch}{1.9}
 \scriptsize
 \color{myblack}
 \centering

\newgeometry{left=4pt,right=4pt, top=1cm}

% INICIO DE QUADROS CONSOLIDADOS

% TABELA 1 GERAL - INVESTIMENTOS POR EMPRESA SEGUNDO FONTES DE RECURSO
\addcontentsline{toc}{section}{ INVESTIMENTOS POR EMPRESA SEGUNDO FONTES DE RECURSO}

<<t1_consolidado, results=tex, echo=F>>=
  
  # INICIO TABELA
  
  dir_loa = gsub("(.+LOA).*", "\\1", getwd())
  dir_latex = paste0(dir_loa, "/volume3/Rnw")
  dir_codigosR = paste0(dir_latex, "/CodigosR")
  dir_utils = paste0(dir_loa, "/utils/")
  dir_data = paste0(dir_loa, "/volume3/data")
  dir_bancos = paste0(dir_loa, "/bancos")
  
  ANO_DOC = as.numeric(readLines(paste(dir_utils, "/ano.txt", sep=""), warn = F))
  source(paste0(dir_utils, "funcoes.R"), encoding = "UTF-8")
  source(paste0(dir_utils, "formataTexto.R"), encoding = "UTF-8")
  
  source(paste0(dir_codigosR, "/T1_INVESTIMENTOS_POR_EMPRESA_SEGUNDO_FONTES_DE_RECURSO.R"), encoding = "UTF-8")
@

\newpage
\phantomsection
% INICIO DE TABELA 2 GERAL - INVESTIMENTOS POR EMPRESA SEGUNDO O DETALHAMENTO DOS INVESTIMENTOS
\addcontentsline{toc}{section}{ INVESTIMENTOS POR EMPRESA SEGUNDO O DETALHAMENTO DOS INVESTIMENTOS}

<<t2_consolidado, results=tex, echo=F>>=
  source(paste0(dir_codigosR, "/T2_INVESTIMENTOS_EMPRESA_SEGUNDO_DETALHAMENTO_INVESTIMENTOS.R"), encoding = "UTF-8")
@

\newpage
\phantomsection
% INICIO DE TABELA3 GERAL - INVESTIMENTOS SEGUNDO FUNÇÕES, SUBFUNÇÕES E PROGRAMAS POR PROJETOS E ATIVIDADES
\addcontentsline{toc}{section}{ INVESTIMENTOS SEGUNDO FUNÇÕES, SUBFUNÇÕES E PROGRAMAS POR PROJETOS E ATIVIDADES}

<<t3_consolidado, results=tex, echo=F>>=
  source(paste0(dir_codigosR,"/T3_INVESTIMENTOS_SEGUNDO_FUNCOES_SUB_PROGRAMAS_PROJETOS_ATIVIDADES.R"), encoding="UTF-8")
@
 
% FIM DE QUADROS CONSOLIDADOS

\newpage
\ifthispageodd{ }{\afterpage{\null\thispagestyle{empty}\newpage}}
\phantomsection
\restoregeometry
\vspace*{9cm}
\addcontentsline{toc}{section}{ RELATÓRIOS POR EMPRESA}
\centering \Huge {\textbf{RELATÓRIOS POR EMPRESA}}
\afterpage{\null\thispagestyle{empty}\newpage}
\newpage

<<Tabelas_porUO, results=tex, echo=FALSE>>=

  sumario = data.table(read.table(paste(dir_data, "/consolidado/sumario_v3.txt", sep=""), header=T, sep="\t",
                                  dec=",", stringsAsFactors = FALSE))


  for(uo in sumario$cod_uo){
    #uo = 5201
    # Capa com o nome de cada UO
    cat("\\ifthispageodd{ }{\\afterpage{\\null\\thispagestyle{empty}\\newpage}}\n")
    cat("\\newpage\n")
    cat("\\restoregeometry\n")
    cat("\\vspace*{1cm}\n")
    cat("\\phantomsection\n")
    cat("\\vspace*{8cm}\n")
    
    cat("\\addcontentsline{toc}{subsection}{", paste(substr(uo,1,1), ".", substr(uo,2,3), ".", substr(uo,4,4), 
                                                     " - ", sumario$uo[sumario$cod_uo==uo] , sep=""),"}\n", sep="")
    
    cat("\\centering \\Huge {\\textbf{",sumario$uo[sumario$cod_uo==uo] ,"}}\n", sep="")
    cat("\\afterpage{\\null\\thispagestyle{empty}\\newpage}\n")
    cat("\\newpage\n")

    cat("\\newgeometry{left=3pt,right=3pt, top=1cm}\n")

    ## Tabela 1: PROGRAMA DE INVESTIMENTO
    
    source(paste0(dir_codigosR,"/T1_relatorio_por_empresa.R"), encoding="UTF-8")
    cat("\\newpage\n")

    ## Tabela 2 - Origem de Recursos para Investimento
    source(paste0(dir_codigosR,"/T2_ORIGENS_RECURSOS_INVESTIMENTOS.R"), encoding="UTF-8")
    cat("\\newpage\n")
 
    ## Tabela 3 - RECURSOS FINANCEIROS FONTE DE RECURSOS E APLICAÇÃO - INVESTIMENTO 
    source(paste0(dir_codigosR,"/T3_RECURSOS_FINANCEIROS_FONTE_RECURSOS_APLICACAO_INVESTIMENTO.R"), encoding="UTF-8")
    cat("\\newpage\n")
  
    ## Tabela 4 - Detalhamento de Investimentos 
    source(paste0(dir_codigosR,"/T4_DETALHAMENTO_INVESTIMENTOS.R"), encoding="UTF-8")
    cat("\\newpage\n") 

    ## Tabela 5 - QUADRO DE DETALHAMENTO DE INVESTIMENTO
    source(paste0(dir_codigosR,"/T5_QUADRO_DETALHAMENTO_INVESTIMENTO.R"), encoding="UTF-8")
    cat("\\newpage\n") 
  
    } 


@

\newpage
\ifthispageodd{ }{\afterpage{\null\thispagestyle{empty}\newpage}}
\phantomsection
\restoregeometry
\vspace*{9cm}
\addcontentsline{toc}{section}{ ORIGEM DE RECURSOS PARA INVESTIMENTO E DETALHAMENTO DOS INVESTIMENTOS}
\centering \Huge {\textbf{ORIGEM DE RECURSOS PARA INVESTIMENTO E DETALHAMENTO DOS INVESTIMENTOS}}
\afterpage{\null\thispagestyle{empty}\newpage}
\newpage

% Inicio de Anexo
\renewcommand*{\arraystretch}{1.2}
 \normalsize
 \color{myblack}
 \centering
 
\newgeometry{top=1cm}
\addcontentsline{toc}{section}{ ORIGEM DE RECURSOS PARA INVESTIMENTO}

<<Anexo_Origem_Recursos_Investimentos, results=tex, echo=FALSE>>=
  source(paste0(dir_codigosR,"/ANEXO_ORIGEM_DE_RECURSOS_PARA_INVESTIMENTO.R"), encoding="UTF-8")
@

\newpage
\phantomsection
\addcontentsline{toc}{section}{DETALHAMENTO DOS INVESTIMENTOS}

<<Anexo_Detalhamento_Investimentos, results=tex, echo=FALSE>>=
  source(paste0(dir_codigosR,"/ANEXO_DETALHAMENTO_INVESTIMENTOS.R"), encoding="UTF-8")
  
  # FIM TABELA
  
@

% \newgeometry{top=0cm, right=0cm, left=-6cm, bottom=0cm}
% \includepdf[pages={153},scale=1.1]{04_LOA_Volume_III.pdf}

\end{document}