\documentclass{article}

\input{load_bibliotecas}

\begin{document}
\SweaveOpts{concordance=TRUE}

\scriptsize

\renewcommand*{\arraystretch}{1.9}
 \scriptsize
 \color{myblack}
 \centering
 

\newgeometry{left=3pt,right=3pt, top=1cm}
<<results=tex, echo=FALSE>>=

  dir_loa = gsub("(.+LOA).*", "\\1", getwd())
  dir_latex = paste0(dir_loa, "/volume3/Rnw")
  dir_codigosR = paste0(dir_latex, "/CodigosR")
  dir_utils = paste0(dir_loa, "/utils/")
  dir_data = paste0(dir_loa, "/volume3/data")
  dir_bancos = paste0(dir_loa, "/bancos")

  ANO_DOC = as.numeric(readLines(paste(dir_utils, "/ano.txt", sep=""), warn = F))
  
  source(paste0(dir_utils, "funcoes.R"), encoding = "UTF-8")

  sumario = data.table(read.table(paste(dir_data, "/consolidado/sumario_v3.txt", sep=""), header=T, sep="\t",
                                  dec=",", stringsAsFactors = FALSE))

  for(uo in sumario[, cod_uo]){

    # INICIO TABELA
    t2 = data.table(
      readr::read_delim(
      file = paste(dir_data, "/tabela2/", uo,".txt", sep=""), 
      delim = "\t", 
      locale = readr::locale('pt', decimal_mark = ',', encoding = 'Latin1'),
      col_types = readr::cols(.default = 'c', nivel = 'i')
      )
    )    
    
    t2[is.na(t2)] = ""
    
    t2$nivel = ifelse(t2$nivel!=1, t2$nivel*2, t2$nivel)
    
    cat("\\noindent\\begin{longtable}[c]{m{8cm}|m{3cm}|m{3cm}}\n")
    
    titulo =  paste0("\\multicolumn{3}{c}{\\cellcolor{gray!50} \\textcolor{myblack} {\\normalsize \\textbf{",
                     "ORIGENS DE RECURSOS PARA INVESTIMENTOS}}}\\TBstrut  \\\\[2ex]\n")
    
    subtitulo = paste("\\multicolumn{2}{l}{\\textbf{Exercício: \\textcolor{myblack}{", ANO_DOC ,
                  "}}} & \\multicolumn{1}{r}{R\\$1,00} \\\\\n")

    titulo_orgao = paste("\\multicolumn{3}{L{14cm}}{\\textbf{ÓRGÃO:} ", t2[1,orgao] , "} \\\\\n", sep="")
    titulo_uo = paste("\\multicolumn{3}{L{14cm}}{\\textbf{UO:} \\hspace{12pt} ",t2[1, uo], "} \\\\\n", sep="")

    cat(titulo)
    cat("\\specialrule{1.5pt}{2pt}{0pt}\n")
    cat(subtitulo)
    cat(titulo_orgao)
    cat(titulo_uo)
    cat("\\specialrule{1pt}{0pt}{0pt}\n")
 
    variaveis = paste0("\\valorHeader{\\centering \\textbf{ESPECIFICAÇÃO}} & ",
                       "\\valorHeader{\\centering \\textbf{VALOR}} &  ",
                       "\\multicolumn{1}{c}{\\textbf{TOTAL}} \\\\\n")

    cat(variaveis)
 
    cat("\\hline")
    cat("\\endfirsthead")
 
    cat(titulo)
    cat("\\specialrule{1.5pt}{2pt}{0pt}\n")
    cat(subtitulo)
    cat(titulo_orgao)
    cat(titulo_uo)
    cat("\\specialrule{1pt}{0pt}{0pt}\n")
 
    cat(variaveis)
  
    cat("\\hline\n")
    cat("\\endhead\n")
    cat("\\endfoot\n")
    cat("\\hline\n")
    cat("\\hline \\hline\n")
    cat("\\endlastfoot\n")
  
    for(i in 1:nrow(t2)){
      
      if(toupper(t2[i, especificacao])=="TOTAL"){
        
        cat("\\hline \\hline\n")
        
        cat("\\multicolumn{2}{l}{\\textbf{", t2[i, especificacao],
            "}} &  \\multicolumn{1}{r}{\\textbf{", t2[i, total], "}} \\\\\n")
        
      } else if(t2[i, nivel]==1){
        
        cat("\\multicolumn{1}{@{\\hspace{", (t2[i, nivel]-1) ,"em}}L{8cm}|}{ \\textbf{", t2[i, especificacao],
            "}} & \\multicolumn{1}{r|}{ \\textbf{",  t2[i, valor], 
            "}} & \\multicolumn{1}{R{3cm}}{ \\textbf{", t2[i, total],"}} \\\\\n", sep="")
     
        } else{
          
          cat("\\multicolumn{1}{@{\\hspace{", (t2[i, nivel]-1) ,"em}}L{8cm}|}{", t2[i, especificacao],
              "} & \\multicolumn{1}{r|}{",  t2[i, valor], 
              "} & \\multicolumn{1}{R{3cm}}{", t2[i, total],"} \\\\\n", sep="")
        }
      }
 
  cat("\\end{longtable}\n")
  
  # FIM TABELA
  
  cat("\\newpage\n")
  
  }
  
@

\end{document}
